(()=>{'use strict';
const U='https://llmhyezgcnbognmmsnzq.supabase.co',K='sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml',db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>Number(v||0),parseList=v=>[...new Set(String(v||'').split(/[\n,;\s]+/).map(x=>x.trim()).filter(Boolean))];
let snapshot={projects:[],people:[],access:[],templates:[]},selected=new Set(),activeOnly=true,previewRows=[],lastSkipped=[];
function notice(text,error=false){const n=$('notice');n.textContent=text;n.className='notice '+(error?'result err':'result ok')}
function setBusy(v){$('flow').classList.toggle('loading',v);$('refresh').disabled=v}
function project(){return snapshot.projects.find(p=>Number(p.id)===Number($('project').value))||null}
function keys(){const visible=[...selected],bulk=parseList($('bulkPeople').value);return [...new Set([...visible,...bulk])]}
function accessFor(pid,uid){return snapshot.access.find(a=>Number(a.project_id)===Number(pid)&&String(a.user_id)===String(uid))?.status||'not explicit'}
function currentQuery(){const q=$('peopleSearch').value.trim().toLowerCase();return snapshot.people.filter(p=>(!activeOnly||p.account_status==='active')&&(!q||[p.full_name,p.email,p.uid].some(v=>String(v||'').toLowerCase().includes(q))))}
function renderPeople(){const rows=currentQuery();$('peopleList').innerHTML=rows.length?rows.map(p=>{const checked=selected.has(p.email),acc=accessFor($('project').value,p.id);return `<label class="person"><input type="checkbox" data-person="${esc(p.email)}" ${checked?'checked':''}><span><strong>${esc(p.full_name||'Unnamed')}</strong><small>${esc(p.email)} · ${esc(p.uid||'No UID')}</small></span><span class="pill ${p.account_status==='active'?(acc==='revoked'?'pill-warn':'pill-gray'):'pill-warn'}">${p.account_status==='active'?(acc==='revoked'?'project revoked':'active'):'platform '+esc(p.account_status)}</span></label>`}).join(''):'<div class="empty">No people match this search.</div>';$('peopleList').querySelectorAll('[data-person]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.person):selected.delete(c.dataset.person);renderSelection();debouncedPreview()});renderSelection()}
function renderSelection(){const total=keys().length;$('selectedCount').textContent=`${total} selected`;}
function renderProject(){const p=project();if(!p){$('projectSummary').innerHTML='';return}const tx=p.project_type==='transcription',layer=$('layer').value,ready=tx?(layer==='L1'?num(p.tx_l1_ready):num(p.tx_l2_ready)):num(layer==='L1'?p.l1_available:p.l2_available);$('projectSummary').innerHTML=`<div class="sum"><span>Type</span><strong>${esc(p.project_type||'general')}</strong></div><div class="sum"><span>Status</span><strong>${esc(p.lifecycle_status)}</strong></div><div class="sum"><span>${tx?'Ready queue':'Available capacity'}</span><strong>${ready}</strong></div><div class="sum"><span>Rate</span><strong>$${num(layer==='L1'?p.l1_rate:p.l2_rate).toFixed(2)}</strong></div>`;$('capacityOption').classList.toggle('hidden',tx);renderTemplates();renderPeople();debouncedPreview()}
function renderTemplates(){const p=project(),layer=$('layer').value,cur=$('template').value;if(!p)return;const rows=snapshot.templates.filter(t=>Number(t.project_id)===Number(p.id)&&t.layer===layer&&t.is_active);const disabled=p.project_type==='transcription'&&layer==='L1';$('template').disabled=disabled;$('template').innerHTML='<option value="">Standard project task</option>'+rows.map(t=>`<option value="${t.id}">${esc(t.name)} · ${esc(t.task_type||'standard')}${t.price_override!=null?' · $'+num(t.price_override).toFixed(2):''}</option>`).join('');if(rows.some(t=>String(t.id)===String(cur)))$('template').value=cur}
function renderProjects(){const params=new URLSearchParams(location.search),wanted=Number(params.get('project')||0);$('project').innerHTML=snapshot.projects.map(p=>`<option value="${p.id}" ${p.lifecycle_status!=='active'?'disabled':''}>${esc(p.project_name)} · ${esc(p.project_type||'general')}${p.lifecycle_status!=='active'?' · '+esc(p.lifecycle_status):''}</option>`).join('');if(wanted&&snapshot.projects.some(p=>Number(p.id)===wanted&&p.lifecycle_status==='active'))$('project').value=String(wanted);else{const first=snapshot.projects.find(p=>p.lifecycle_status==='active');if(first)$('project').value=String(first.id)}const qLayer=params.get('layer');if(['L1','L2'].includes(qLayer))$('layer').value=qLayer;renderProject()}
async function guard(){setBusy(true);const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return false}const {data:u}=await db.from('users').select('role,accountStatus').eq('id',user.id).maybeSingle();if(!u||u.role!=='admin'||u.accountStatus!=='active'){location.replace('/dashboard');return false}return true}
async function load(){if(!await guard())return;const {data,error}=await db.rpc('admin_assignment_center_snapshot');setBusy(false);if(error){notice(error.message,true);return}snapshot=data||snapshot;renderProjects();renderPeople();await preview()}
async function preview(){const p=project(),list=keys();renderSelection();if(!p||!list.length){previewRows=[];$('previewSummary').textContent='Choose people to preview their current status.';$('previewList').innerHTML='<div class="empty">No people selected.</div>';return}const {data,error}=await db.rpc('admin_assignment_center_preview',{p_project_id:Number(p.id),p_layer:$('layer').value,p_user_keys:list});if(error){$('previewSummary').textContent='Preview unavailable: '+error.message;return}previewRows=Array.isArray(data)?data:[];const target=$('mode').value==='access_only'?null:Math.max(0,Math.min(100,Math.floor(num($('limit').value))));$('previewSummary').textContent=`${list.length} selected · ${p.project_name} · ${$('layer').value}${target==null?' · access only':` · target ${target} open task${target===1?'':'s'} each`}`;$('previewList').innerHTML=previewRows.length?previewRows.map(r=>{if(!r.found)return `<div class="preview-row"><div class="preview-row-head"><strong>${esc(r.key)}</strong><span class="pill pill-warn">not found</span></div></div>`;const revoked=r.access_status==='revoked',inactive=r.account_status!=='active',need=target==null?0:Math.max(target-num(r.open_work),0);return `<div class="preview-row"><div class="preview-row-head"><div><strong>${esc(r.name||r.email)}</strong><small>${esc(r.email)} · ${esc(r.uid||'No UID')}</small></div><span class="pill ${inactive||revoked?'pill-warn':'pill-gray'}">${inactive?'platform '+esc(r.account_status):revoked?'will restore access':esc(r.access_status)}</span></div><div class="preview-metrics"><span class="pill pill-gray">${num(r.open_work)} open</span>${r.remaining!=null?`<span class="pill pill-gray">${num(r.remaining)} remaining</span>`:''}${target!=null?`<span class="pill pill-brand">${need} to add</span>`:''}</div></div>`}).join(''):'<div class="empty">No preview data.</div>'}
let pt;function debouncedPreview(){clearTimeout(pt);pt=setTimeout(preview,220)}
async function apply(){const p=project(),list=keys();if(!p)return notice('Choose a project.',true);if(!list.length)return notice('Choose at least one person.',true);if(p.lifecycle_status!=='active')return notice('Choose an active project.',true);if($('mode').value==='access_only'){setBusy(true);const {data,error}=await db.rpc('admin_bulk_project_access',{p_project_id:Number(p.id),p_user_keys:list,p_status:'active',p_cancel_pending:false});setBusy(false);if(error)return notice(error.message,true);lastSkipped=data?.skipped||[];renderResult({updated:data?.changed||0,results:list.map(k=>({email:k,mode:'access_only',created_now:0})),skipped:lastSkipped},'Project access updated.');await load();return}const limit=Math.floor(num($('limit').value));if(limit<0||limit>100)return notice('Task limit must be between 0 and 100.',true);setBusy(true);const {data,error}=await db.rpc('admin_assignment_center_apply',{p_project_id:Number(p.id),p_layer:$('layer').value,p_user_keys:list,p_target_limit:limit,p_template_id:$('template').value||null,p_grant_access:$('grantAccess').checked,p_auto_capacity:$('autoCapacity').checked});setBusy(false);if(error)return notice(error.message,true);lastSkipped=data?.skipped||[];renderResult(data,'Assignment applied.');await load()}
function renderResult(data,title){const results=data?.results||[],skipped=data?.skipped||[];const made=results.reduce((n,r)=>n+num(r.created_now),0);$('result').innerHTML=`<div class="result ok"><strong>${esc(title)}</strong><br>${results.length} participant${results.length===1?'':'s'} updated · ${made} new task${made===1?'':'s'} created.${skipped.length?`<br>${skipped.length} skipped.`:''}</div>`;$('copySkipped').classList.toggle('hidden',!skipped.length)}
async function revoke(){const p=project(),list=keys();if(!p||!list.length)return notice('Choose a project and at least one person.',true);if(!confirm(`Revoke ${p.project_name} access for ${list.length} selected participant${list.length===1?'':'s'}?`))return;setBusy(true);const {data,error}=await db.rpc('admin_bulk_project_access',{p_project_id:Number(p.id),p_user_keys:list,p_status:'revoked',p_cancel_pending:$('cancelPending').checked});setBusy(false);if(error)return notice(error.message,true);lastSkipped=data?.skipped||[];renderResult({results:list.map(k=>({email:k,created_now:0})),skipped:lastSkipped},`Project access revoked${data?.cancelled_l1||data?.cancelled_l2?` · cancelled L1 ${data.cancelled_l1||0}, L2 ${data.cancelled_l2||0}`:''}.`);await load()}
$('project').onchange=renderProject;$('layer').onchange=renderProject;$('template').onchange=debouncedPreview;$('peopleSearch').oninput=renderPeople;$('bulkPeople').oninput=()=>{renderSelection();debouncedPreview()};$('selectFiltered').onclick=()=>{currentQuery().forEach(p=>selected.add(p.email));renderPeople();debouncedPreview()};$('clearPeople').onclick=()=>{selected.clear();$('bulkPeople').value='';renderPeople();preview()};$('activeOnly').onclick=()=>{activeOnly=!activeOnly;$('activeOnly').textContent=activeOnly?'Active accounts only':'Showing all accounts';renderPeople()};document.querySelectorAll('[data-limit]').forEach(b=>b.onclick=()=>{$('limit').value=b.dataset.limit;debouncedPreview()});$('limit').oninput=debouncedPreview;$('mode').onchange=()=>{const access=$('mode').value==='access_only';$('limit').disabled=access;document.querySelectorAll('[data-limit]').forEach(b=>b.disabled=access);debouncedPreview()};$('grantAccess').onchange=debouncedPreview;$('autoCapacity').onchange=debouncedPreview;$('previewBtn').onclick=preview;$('apply').onclick=apply;$('revoke').onclick=revoke;$('refresh').onclick=load;$('copySkipped').onclick=async()=>{const text=lastSkipped.map(x=>`${x.key||x.email||''}\t${x.reason||'Skipped'}`).join('\n');try{await navigator.clipboard.writeText(text);notice('Skipped people copied.')}catch(_){notice(text||'No skipped people.')}};
load();
})();