(()=>{'use strict';
const U='https://llmhyezgcnbognmmsnzq.supabase.co',K='sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml',db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>Number(v||0);
let snapshot={projects:[],people:[],access:[]},person=null,project=null,layer='L1',previewRow=null,busy=false,previewSeq=0;
const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?';
const target=()=>Math.max(1,Math.min(100,Math.floor(num($('taskTarget').value)||1)));
function setBusy(v){busy=v;document.body.classList.toggle('qa-loading',v);$('refresh').disabled=v;$('assign').disabled=v||!ready()}
function showError(text=''){const el=$('error');el.textContent=text;el.classList.toggle('visible',!!text)}
function ready(){return !!(person&&project&&layer&&target()>=1)}
function accessFor(){return snapshot.access.find(a=>Number(a.project_id)===Number(project?.id)&&String(a.user_id)===String(person?.id))?.status||'not explicit'}
function projectCapacity(){if(!project)return null;const tx=project.project_type==='transcription';if(tx)return num(layer==='L1'?project.tx_l1_ready:project.tx_l2_ready);return num(layer==='L1'?project.l1_available:project.l2_available)}
function activate(){
 const states=[!!person,!!project,!!layer&&!!project,ready()];
 const ids=['progPerson','progProject','progStage','progTasks'];
 ids.forEach((id,i)=>{const el=$(id);el.classList.toggle('done',states[i]&&(i<3||ready()));el.classList.toggle('active',!states[i]&&(i===0||states.slice(0,i).every(Boolean)))});
 const secProject=$('secProject'),secStage=$('secStage'),secTasks=$('secTasks'),secReview=$('secReview');
 secProject.classList.toggle('locked',!person);secProject.classList.toggle('active',!!person&&!project);secProject.classList.toggle('complete',!!project);
 secStage.classList.toggle('locked',!project);secStage.classList.toggle('active',!!project);secStage.classList.toggle('complete',!!project&&!!layer);
 secTasks.classList.toggle('locked',!project);secTasks.classList.toggle('active',!!project);secTasks.classList.toggle('complete',ready());
 secReview.classList.toggle('locked',!ready());secReview.classList.toggle('active',ready());
 $('projectSearch').disabled=!person;document.querySelectorAll('[data-layer]').forEach(b=>b.disabled=!project);$('taskTarget').disabled=!project;$('minus').disabled=!project;$('plus').disabled=!project;document.querySelectorAll('[data-target]').forEach(b=>b.disabled=!project);
 $('assign').disabled=busy||!ready();$('status').textContent=ready()?'Checking current assignment…':person?'Choose a project to continue.':'Choose a participant to begin.';
}
function renderPersonSelected(){const box=$('participantSelected');if(!person){box.classList.remove('visible');box.innerHTML='';return}box.innerHTML=`<div class="qa-avatar">${esc(initials(person.full_name))}</div><div class="qa-selected-copy"><strong>${esc(person.full_name||'Unnamed participant')}</strong><small>${esc(person.email)} · ${esc(person.uid||'No UID')}</small></div><button class="qa-change" type="button" data-change="person">Change</button>`;box.classList.add('visible');$('participantSearch').value='';$('participantOptions').classList.remove('open')}
function renderProjectSelected(){const box=$('projectSelected');if(!project){box.classList.remove('visible');box.innerHTML='';return}const cap=projectCapacity();box.innerHTML=`<div class="qa-avatar">P</div><div class="qa-selected-copy"><strong>${esc(project.project_name)}</strong><small>${esc(project.project_type||'general')} · ${layer} · ${cap} ${project.project_type==='transcription'?'ready':'available'}</small></div><button class="qa-change" type="button" data-change="project">Change</button>`;box.classList.add('visible');$('projectSearch').value='';$('projectOptions').classList.remove('open')}
function renderPeople(q=''){q=String(q).trim().toLowerCase();const rows=snapshot.people.filter(p=>p.account_status==='active'&&(!q||[p.full_name,p.email,p.uid].some(v=>String(v||'').toLowerCase().includes(q)))).slice(0,10);$('participantOptions').innerHTML=rows.length?rows.map(p=>`<button type="button" class="qa-option" data-person="${esc(p.id)}"><div class="qa-avatar">${esc(initials(p.full_name))}</div><div class="qa-option-copy"><strong>${esc(p.full_name||'Unnamed participant')}</strong><small>${esc(p.email)} · ${esc(p.uid||'No UID')}</small></div><span class="qa-option-meta">Active</span></button>`).join(''):'<div class="qa-empty">No active participant matches this search.</div>';$('participantOptions').classList.add('open')}
function renderProjects(q=''){q=String(q).trim().toLowerCase();const rows=snapshot.projects.filter(p=>p.lifecycle_status==='active'&&(!q||[p.project_name,p.project_type,p.id].some(v=>String(v||'').toLowerCase().includes(q)))).slice(0,10);$('projectOptions').innerHTML=rows.length?rows.map(p=>{const tx=p.project_type==='transcription',cap=num(layer==='L1'?(tx?p.tx_l1_ready:p.l1_available):(tx?p.tx_l2_ready:p.l2_available));return `<button type="button" class="qa-option" data-project="${esc(p.id)}"><div class="qa-avatar">P</div><div class="qa-option-copy"><strong>${esc(p.project_name)}</strong><small>${esc(p.project_type||'general')} · Project #${esc(p.id)}</small></div><span class="qa-option-meta">${cap} ${tx?'ready':'available'}</span></button>`}).join(''):'<div class="qa-empty">No active project matches this search.</div>';$('projectOptions').classList.add('open')}
function selectPerson(id){person=snapshot.people.find(p=>String(p.id)===String(id))||null;project=null;previewRow=null;renderPersonSelected();renderProjectSelected();activate();renderReview();if(person){setTimeout(()=>$('projectSearch').focus(),120)}}
function selectProject(id){project=snapshot.projects.find(p=>Number(p.id)===Number(id))||null;previewRow=null;renderProjectSelected();activate();schedulePreview()}
function setLayer(next){if(!['L1','L2'].includes(next))return;layer=next;document.querySelectorAll('[data-layer]').forEach(b=>{const on=b.dataset.layer===layer;b.classList.toggle('active',on);b.querySelector('.qa-stage-badge').textContent=on?'SELECTED':''});renderProjectSelected();schedulePreview()}
function renderReview(){const grid=$('reviewGrid');if(!ready()){grid.innerHTML='<div class="qa-summary">Complete the four steps above to preview this assignment.</div>';$('assign').disabled=true;return}const cap=projectCapacity(),open=previewRow?.found?num(previewRow.open_work):null,need=open==null?null:Math.max(target()-open,0),acc=previewRow?.found?previewRow.access_status:accessFor();grid.innerHTML=`<div class="qa-review-card"><span>Participant</span><strong>${esc(person.full_name||person.email)}</strong><small>${esc(person.email)}</small></div><div class="qa-review-card"><span>Project & stage</span><strong>${esc(project.project_name)} · ${layer}</strong><small>${esc(project.project_type||'general')} · ${cap} ${project.project_type==='transcription'?'ready':'available'} now</small></div><div class="qa-review-card"><span>Current open work</span><strong>${open==null?'Checking…':open}</strong><small>${acc==='revoked'?'Project access will be restored automatically.':`Access: ${esc(acc||'not explicit')}`}</small></div><div class="qa-review-card"><span>Target open tasks</span><strong>${target()}</strong><small>${need==null?'Calculating…':need?`${need} new task${need===1?'':'s'} will be added.`:'No new tasks needed. Existing work is not removed.'}</small></div><div class="qa-summary"><strong>${need==null?'Preparing preview…':need?`Ready to add ${need} task${need===1?'':'s'}.`:'Target already met.'}</strong> Adatacore tops this participant up to ${target()} open ${layer} task${target()===1?'':'s'} and keeps any work already in progress.</div>`;$('assign').disabled=busy||open==null||!previewRow?.found;$('status').textContent=open==null?'Checking current assignment…':previewRow?.found?'Ready to assign.':'Participant preview unavailable.'}
let timer;function schedulePreview(){clearTimeout(timer);renderReview();if(!ready())return;timer=setTimeout(preview,180)}
async function preview(){if(!ready())return;const seq=++previewSeq;const {data,error}=await db.rpc('admin_assignment_center_preview',{p_project_id:Number(project.id),p_layer:layer,p_user_keys:[person.email]});if(seq!==previewSeq)return;if(error){showError(error.message);previewRow=null;renderReview();return}showError('');previewRow=Array.isArray(data)?data[0]||null:null;renderReview()}
function success(data){const results=data?.results||[],made=results.reduce((n,r)=>n+num(r.created_now),0),box=$('result');box.innerHTML=`<div class="qa-result-icon">✓</div><div><strong>Assignment applied</strong><p>${esc(person.full_name||person.email)} now has the requested ${layer} assignment target. ${made} new task${made===1?'':'s'} created${data?.skipped?.length?' · '+data.skipped.length+' skipped':''}.</p></div>`;box.classList.add('visible')}
async function apply(){if(!ready()||busy)return;showError('');$('result').classList.remove('visible');setBusy(true);const {data,error}=await db.rpc('admin_assignment_center_apply',{p_project_id:Number(project.id),p_layer:layer,p_user_keys:[person.email],p_target_limit:target(),p_template_id:null,p_grant_access:true,p_auto_capacity:true});setBusy(false);if(error){showError(error.message);return}success(data);await preview()}
async function guard(){const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return false}const {data:access,error}=await db.rpc('get_my_admin_access');if(error||!access?.allowed||(!access.is_super_admin&&!access.capabilities?.includes('assignments'))){location.replace('/admin');return false}const badge=document.querySelector('.qa-actions .pill');if(badge&&!access.is_super_admin)badge.textContent='Scoped admin · Project Manager';return true}
async function load(){if(!await guard())return;setBusy(true);const {data,error}=await db.rpc('admin_assignment_center_snapshot');setBusy(false);if(error){showError(error.message);return}snapshot=data||snapshot;const params=new URLSearchParams(location.search),pid=Number(params.get('project')||0),ql=params.get('layer');if(['L1','L2'].includes(ql))setLayer(ql);if(pid){const p=snapshot.projects.find(x=>Number(x.id)===pid&&x.lifecycle_status==='active');if(p){project=p;renderProjectSelected()}}activate();renderReview()}
$('participantSearch').addEventListener('focus',e=>renderPeople(e.target.value));$('participantSearch').addEventListener('input',e=>renderPeople(e.target.value));$('projectSearch').addEventListener('focus',e=>{if(person)renderProjects(e.target.value)});$('projectSearch').addEventListener('input',e=>{if(person)renderProjects(e.target.value)});
$('participantOptions').addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(b)selectPerson(b.dataset.person)});$('projectOptions').addEventListener('click',e=>{const b=e.target.closest('[data-project]');if(b)selectProject(b.dataset.project)});
document.addEventListener('click',e=>{if(!e.target.closest('.qa-search-wrap'))document.querySelectorAll('.qa-dropdown').forEach(d=>d.classList.remove('open'));const c=e.target.closest('[data-change]');if(c?.dataset.change==='person'){person=null;project=null;previewRow=null;renderPersonSelected();renderProjectSelected();activate();renderReview();setTimeout(()=>$('participantSearch').focus(),30)}if(c?.dataset.change==='project'){project=null;previewRow=null;renderProjectSelected();activate();renderReview();setTimeout(()=>$('projectSearch').focus(),30)}});
document.querySelectorAll('[data-layer]').forEach(b=>b.addEventListener('click',()=>setLayer(b.dataset.layer)));document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>{$('taskTarget').value=b.dataset.target;schedulePreview()}));$('minus').onclick=()=>{$('taskTarget').value=Math.max(1,target()-1);schedulePreview()};$('plus').onclick=()=>{$('taskTarget').value=Math.min(100,target()+1);schedulePreview()};$('taskTarget').oninput=()=>{const v=Math.max(1,Math.min(100,Math.floor(num($('taskTarget').value)||1)));if(String(v)!=$('taskTarget').value)$('taskTarget').value=v;schedulePreview()};$('assign').onclick=apply;$('refresh').onclick=load;
load();
})();