(()=>{'use strict';
const URL='https://llmhyezgcnbognmmsnzq.supabase.co',KEY='sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml';
const $=id=>document.getElementById(id);let db=null,state={overview:{},sources:[],datasets:[],benchmarks:[],training_runs:[],models:[],projects:[]};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:3});
const date=v=>v?new Date(v).toLocaleString(): '—';
function toast(msg,error=false){const el=$('coreforgeToast');if(!el)return;el.textContent=msg;el.className='cf-toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='cf-toast',3300)}
function empty(text){return `<div class="cf-empty">${esc(text)}</div>`}
function rightsLabel(v){return ({unknown:'Unknown',adatacore_trainable:'Adatacore trainable',client_private_only:'Private model only',client_exclusive:'Client exclusive',evaluation_only:'Evaluation only'})[v]||v}
function taskLabel(v){return ({asr:'Speech Recognition',audio_qa:'Audio QA',transcript_alignment:'Transcript Alignment',naturalness:'Naturalness',emotion:'Emotion'})[v]||v||'Other'}

function bindTabs(){document.querySelectorAll('.cf-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.cf-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.cf-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))}))}
function bindDialogs(){document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.open)?.showModal()));document.querySelectorAll('.cf-dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close('cancel')}));document.querySelectorAll('.cf-dialog .cf-icon-btn,.cf-dialog .cf-dialog-actions .ghost').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();b.closest('dialog')?.close('cancel')}))}

async function guard(){if(!window.supabase?.createClient){toast('Secure data client did not load. Refresh the page.',true);return false}db=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return false}const {data:access,error}=await db.rpc('get_my_admin_access');if(error||!access?.allowed){location.replace('/workspace');return false}if(access.is_super_admin!==true){location.replace('/admin');return false}return true}
async function load(){const {data,error}=await db.rpc('coreforge_snapshot');if(error){toast(error.message||'Unable to load CoreForge',true);return}state=data||state;render()}

function render(){renderOverview();renderSources();renderDatasets();renderBenchmarks();renderRuns();renderModels();populateForms()}
function renderOverview(){const o=state.overview||{};const metrics=[['Trainable hours',fmt(o.trainable_hours),'Approved by rights registry'],['Data sources',fmt(o.sources),`${fmt(o.unknown_rights)} rights review pending`],['Frozen datasets',fmt(o.frozen_datasets),`${fmt(o.datasets)} total dataset versions`],['Training runs',fmt(o.training_runs),'Worker execution not connected yet'],['Production models',fmt(o.production_models),'Promotion controls arrive with deployment stage']];$('overviewMetrics').innerHTML=metrics.map(x=>`<div class="cf-metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
const stages=[['Rights',Number(o.trainable_sources)>0&&Number(o.unknown_rights)===0,'Classify every source'],['Dataset',Number(o.frozen_datasets)>0,'Freeze exact manifest'],['Benchmark',Number(o.benchmarks)>0,'Create held-out evaluation'],['Training',Number(o.training_runs)>0,'Queue experiment'],['Shadow',state.models.some(m=>['shadow','pilot','production'].includes(m.status)),'Compare against baseline']];$('readinessPipeline').innerHTML=stages.map(([n,ok,t])=>`<div class="cf-step ${ok?'ready':'blocked'}"><b>${n}</b><span>${ok?'Ready':t}</span></div>`).join('');
const src=state.sources||[],max=Math.max(1,...src.map(s=>Number(s.live_hours||0)));$('sourceBars').innerHTML=src.length?src.map(s=>`<div class="cf-bar-line"><span>${esc(s.source_name)}</span><div class="cf-bar-track"><div class="cf-bar-fill" style="width:${Math.max(2,Number(s.live_hours||0)/max*100)}%"></div></div><strong>${fmt(s.live_hours)}h</strong></div>`).join(''):empty('No registered data sources yet.');}
function renderSources(){const rows=$('sourceRows');if(!state.sources?.length){rows.innerHTML='<tr><td colspan="6">No CoreForge sources registered.</td></tr>';return}rows.innerHTML=state.sources.map(s=>`<tr><td><strong>${esc(s.source_name)}</strong><small>${esc(s.source_kind)}${s.project_id?' · project '+s.project_id:''}</small></td><td>${esc(s.language||'—')}</td><td><strong>${fmt(s.live_item_count)} items</strong><small>${fmt(s.live_hours)} hours · ${fmt(s.transcript_segments)} segments</small></td><td>${fmt(s.reviewed_items)} items</td><td><span class="rights ${esc(s.rights_status)}">${esc(rightsLabel(s.rights_status))}</span>${s.rights_basis?`<small>${esc(s.rights_basis)}</small>`:''}</td><td><button class="cf-btn ghost edit-source" data-id="${s.id}" type="button">Edit</button></td></tr>`).join('');document.querySelectorAll('.edit-source').forEach(b=>b.onclick=()=>editSource(b.dataset.id))}
function renderDatasets(){const rows=$('datasetRows');if(!state.datasets?.length){rows.innerHTML='<tr><td colspan="7">No datasets yet. First classify a source as Adatacore trainable.</td></tr>';return}rows.innerHTML=state.datasets.map(d=>`<tr><td><strong>${esc(d.name)}</strong><small>v${d.version} · ${date(d.created_at)}</small></td><td>${esc(taskLabel(d.task))}</td><td>${esc(d.language||'—')}</td><td>${fmt(d.item_count)}</td><td>${fmt(d.total_hours)}</td><td><span class="rights ${d.status==='frozen'?'adatacore_trainable':'unknown'}">${esc(d.status)}</span></td><td>${d.status==='draft'?`<button class="cf-btn primary freeze-dataset" data-id="${d.id}" type="button">Freeze</button>`:'—'}</td></tr>`).join('');document.querySelectorAll('.freeze-dataset').forEach(b=>b.onclick=()=>freezeDataset(b.dataset.id))}
function renderBenchmarks(){const el=$('benchmarkRows');el.innerHTML=state.benchmarks?.length?state.benchmarks.map(b=>`<article class="cf-list-card"><div><strong>${esc(b.name)} · v${b.version}</strong><p>${esc(taskLabel(b.task))} · ${esc(b.language||'all')} · ${fmt(b.item_count)} items · ${fmt(b.total_hours)}h</p></div><span class="rights ${b.status==='frozen'?'adatacore_trainable':'unknown'}">${esc(b.status)}</span></article>`).join(''):empty('No benchmark yet. Create a held-out evaluation dataset before trusting model metrics.')}
function renderRuns(){const el=$('runRows');el.innerHTML=state.training_runs?.length?state.training_runs.map(r=>`<article class="cf-list-card"><div><strong>${esc(r.run_code)} · ${esc(r.name)}</strong><p>${esc(taskLabel(r.task))} · ${esc(r.language||'—')} · base: ${esc(r.base_model||'not specified')} · ${esc(r.compute_type)}</p></div><span class="rights ${r.status==='completed'?'adatacore_trainable':'unknown'}">${esc(r.status)}</span></article>`).join(''):empty('No training runs. CoreForge will record a run before any external worker gets permission to train.')}
function renderModels(){const el=$('modelRows');el.innerHTML=state.models?.length?state.models.map(m=>`<article class="cf-list-card"><div><strong>${esc(m.name)} ${esc(m.version)}</strong><p>${esc(taskLabel(m.task))} · ${esc(m.language||'—')} · ${esc(m.base_model||'base model not recorded')} · registered ${date(m.created_at)}</p></div><span class="rights ${m.status==='production'?'adatacore_trainable':'unknown'}">${esc(m.status)}</span></article>`).join(''):empty('No models registered. A trained artifact starts as a candidate; production promotion is intentionally not enabled yet.')}

function populateForms(){const projects=state.projects||[];$('sourceProject').innerHTML='<option value="">Manual / other source</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.project_name)} · ${fmt(p.audio_hours)}h</option>`).join('');const trainable=state.sources.filter(s=>s.rights_status==='adatacore_trainable');$('datasetSources').innerHTML=trainable.length?trainable.map(s=>`<div class="cf-source-option"><label><input type="checkbox" value="${s.id}"> ${esc(s.source_name)}</label><span>${fmt(s.live_hours)}h</span></div>`).join(''):empty('No sources are marked Adatacore trainable yet.');const frozen=state.datasets.filter(d=>d.status==='frozen');const dsOpts=frozen.map(d=>`<option value="${d.id}">${esc(d.name)} v${d.version} · ${fmt(d.total_hours)}h</option>`).join('');$('benchmarkDataset').innerHTML='<option value="">Independent / manual benchmark</option>'+dsOpts;$('runDataset').innerHTML=dsOpts||'<option value="">No frozen dataset available</option>';$('modelDataset').innerHTML='<option value="">None</option>'+state.datasets.map(d=>`<option value="${d.id}">${esc(d.name)} v${d.version}</option>`).join('');$('modelRun').innerHTML='<option value="">None</option>'+state.training_runs.map(r=>`<option value="${r.id}">${esc(r.run_code)} · ${esc(r.name)}</option>`).join('');$('modelBenchmark').innerHTML='<option value="">None</option>'+state.benchmarks.map(b=>`<option value="${b.id}">${esc(b.name)} v${b.version}</option>`).join('')}
function editSource(id){const s=state.sources.find(x=>x.id===id);if(!s)return;$('sourceId').value=s.id;$('sourceProject').value=s.project_id||'';$('sourceName').value=s.source_name||'';$('sourceLanguage').value=s.language||'';$('sourceKind').value=s.source_kind||'transcription_project';$('sourceRights').value=s.rights_status||'unknown';$('sourceBasis').value=s.rights_basis||'';$('sourceNotes').value=s.rights_notes||'';$('sourceDialog').showModal()}

async function freezeDataset(id){if(!confirm('Freeze this dataset? CoreForge will snapshot the exact eligible audio IDs and transcript hashes for this version.'))return;const {data,error}=await db.rpc('coreforge_freeze_dataset',{p_dataset_id:id});if(error||!data){toast(error?.message||'Dataset could not be frozen.',true);return}toast('Dataset frozen with immutable manifest.');await load()}
function bindForms(){
$('sourceProject').addEventListener('change',()=>{const p=state.projects.find(x=>String(x.id)===$('sourceProject').value);if(p){$('sourceName').value=p.project_name;$('sourceLanguage').value=p.transcription_language||'';$('sourceKind').value='transcription_project'}});
$('sourceDialog').addEventListener('close',()=>{if($('sourceDialog').returnValue==='cancel')return;$('sourceId').value=''})
$('sourceForm').addEventListener('submit',async e=>{e.preventDefault();const args={p_id:$('sourceId').value||null,p_source_kind:$('sourceKind').value,p_project_id:$('sourceProject').value?Number($('sourceProject').value):null,p_source_name:$('sourceName').value.trim(),p_language:$('sourceLanguage').value.trim(),p_modality:'speech',p_rights_status:$('sourceRights').value,p_rights_basis:$('sourceBasis').value.trim(),p_rights_notes:$('sourceNotes').value.trim()};const {error}=await db.rpc('coreforge_save_source',args);if(error){toast(error.message,true);return}$('sourceDialog').close('saved');$('sourceForm').reset();$('sourceId').value='';toast('Training source saved.');await load()});
$('datasetForm').addEventListener('submit',async e=>{e.preventDefault();const ids=[...document.querySelectorAll('#datasetSources input:checked')].map(x=>x.value);const {error}=await db.rpc('coreforge_create_dataset',{p_name:$('datasetName').value.trim(),p_task:$('datasetTask').value,p_language:$('datasetLanguage').value.trim(),p_source_ids:ids,p_criteria:{reviewed_only:$('datasetReviewedOnly').checked}});if(error){toast(error.message,true);return}$('datasetDialog').close('saved');$('datasetForm').reset();toast('Dataset draft created. Freeze it when the criteria are final.');await load()});
$('benchmarkForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.rpc('coreforge_create_benchmark',{p_name:$('benchmarkName').value.trim(),p_task:$('benchmarkTask').value,p_language:$('benchmarkLanguage').value.trim(),p_dataset_id:$('benchmarkDataset').value||null,p_notes:$('benchmarkNotes').value.trim()});if(error){toast(error.message,true);return}$('benchmarkDialog').close('saved');$('benchmarkForm').reset();toast('Benchmark registered. Keep benchmark items out of training.');await load()});
$('runForm').addEventListener('submit',async e=>{e.preventDefault();const ds=state.datasets.find(x=>x.id===$('runDataset').value);const {error}=await db.rpc('coreforge_create_training_run',{p_name:$('runName').value.trim(),p_task:$('runTask').value,p_language:$('runLanguage').value.trim(),p_dataset_id:$('runDataset').value||null,p_base_model:$('runBaseModel').value.trim(),p_compute_type:$('runCompute').value,p_config:{dataset_version:ds?.version||null}});if(error){toast(error.message,true);return}$('runDialog').close('saved');$('runForm').reset();toast('Training run queued. No compute has been started.');await load()});
$('modelForm').addEventListener('submit',async e=>{e.preventDefault();let metrics={};try{metrics=$('modelMetrics').value.trim()?JSON.parse($('modelMetrics').value):{}}catch(_){toast('Metrics must be valid JSON.',true);return}const {error}=await db.rpc('coreforge_register_model',{p_name:$('modelName').value.trim(),p_task:$('modelTask').value,p_language:$('modelLanguage').value.trim(),p_version:$('modelVersion').value.trim(),p_training_run_id:$('modelRun').value||null,p_dataset_id:$('modelDataset').value||null,p_benchmark_id:$('modelBenchmark').value||null,p_base_model:$('modelBaseModel').value.trim(),p_metrics:metrics,p_notes:$('modelNotes').value.trim()});if(error){toast(error.message,true);return}$('modelDialog').close('saved');$('modelForm').reset();toast('Model candidate registered.');await load()});}

window.addEventListener('DOMContentLoaded',async()=>{bindTabs();bindDialogs();bindForms();$('refreshCoreForge').onclick=load;try{if(await guard())await load()}catch(error){toast(error.message||'CoreForge failed to initialize.',true)}});
})();