(()=>{'use strict';
const URL='https://llmhyezgcnbognmmsnzq.supabase.co',KEY='sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml';
const $=id=>document.getElementById(id);let db=null,state={overview:{},sources:[],datasets:[],benchmarks:[],training_runs:[],models:[],projects:[],open_connectors:[],workers:[],auto_policies:[]};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:3});
const date=v=>v?new Date(v).toLocaleString():'—';
const ago=v=>{if(!v)return'Never';const s=Math.max(0,(Date.now()-new Date(v).getTime())/1000);if(s<60)return`${Math.round(s)}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`};
function toast(msg,error=false){const el=$('coreforgeToast');if(!el)return;el.textContent=msg;el.className='cf-toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='cf-toast',3600)}
function empty(text){return `<div class="cf-empty">${esc(text)}</div>`}
function rightsLabel(v){return({unknown:'Unknown',adatacore_trainable:'Adatacore trainable',client_private_only:'Private model only',client_exclusive:'Client exclusive',evaluation_only:'Evaluation only'})[v]||v}
function taskLabel(v){return({asr:'Speech Recognition',audio_qa:'Audio QA',transcript_alignment:'Transcript Alignment',naturalness:'Naturalness',emotion:'Emotion'})[v]||v||'Other'}
function statusClass(v){return['connected','online','busy','completed','candidate','complete'].includes(v)?'adatacore_trainable':['failed','revoked','error'].includes(v)?'client_exclusive':'unknown'}

function bindTabs(){document.querySelectorAll('.cf-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.cf-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.cf-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab));history.replaceState(null,'',`#${b.dataset.tab}`)}));const hash=location.hash.slice(1);if(hash){document.querySelector(`.cf-tabs button[data-tab="${CSS.escape(hash)}"]`)?.click()}}
function bindDialogs(){document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.open)?.showModal()));document.querySelectorAll('.cf-dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close('cancel')}));document.querySelectorAll('.cf-dialog .cf-icon-btn,.cf-dialog .cf-dialog-actions .ghost').forEach(b=>{if(b.id==='closeWorkerToken')return;b.addEventListener('click',e=>{if(b.closest('#workerTokenDialog'))return;e.preventDefault();b.closest('dialog')?.close('cancel')})})}

async function guard(){if(!window.supabase?.createClient){toast('Secure data client did not load. Refresh the page.',true);return false}db=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return false}const {data:access,error}=await db.rpc('get_my_admin_access');if(error||!access?.allowed){location.replace('/workspace');return false}if(access.is_super_admin!==true){location.replace('/admin');return false}return true}
async function load(){const {data,error}=await db.rpc('coreforge_snapshot');if(error){toast(error.message||'Unable to load CoreForge',true);return}state={...state,...(data||{})};render()}

function render(){renderOverview();renderOpenConnectors();renderSources();renderDatasets();renderBenchmarks();renderRuns();renderModels();renderWorkers();renderPolicies();populateForms()}
function renderOverview(){const o=state.overview||{};const metrics=[['Trainable local hours',fmt(o.trainable_hours),'Human/project data with approved rights'],['Open connectors',fmt(o.open_connectors),'Licensed remote sources'],['Workers online',fmt(o.workers_online),'Seen in the last 5 minutes'],['Queued runs',fmt(o.queued_runs),'Waiting for compute'],['Frozen datasets',fmt(o.frozen_datasets),`${fmt(o.datasets)} total versions`],['Production models',fmt(o.production_models),'Candidates never auto-promote']];$('overviewMetrics').innerHTML=metrics.map(x=>`<div class="cf-metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
const stages=[['Rights',Number(o.trainable_sources)>0,'At least one trainable source'],['Open data',state.open_connectors.some(c=>c.source_id),'Connect licensed bootstrap data'],['Dataset',Number(o.frozen_datasets)>0,'Freeze exact lineage'],['Worker',Number(o.workers_online)>0,'Connect GPU compute'],['Training',state.training_runs.some(r=>['training','evaluating','completed'].includes(r.status)),'Worker claims queued run'],['Shadow',state.models.some(m=>['shadow','pilot','production'].includes(m.status)),'Compare against baseline']];$('readinessPipeline').innerHTML=stages.map(([n,ok,t])=>`<div class="cf-step ${ok?'ready':'blocked'}"><b>${n}</b><span>${ok?'Ready':t}</span></div>`).join('');
const src=(state.sources||[]).filter(s=>s.source_kind!=='open_dataset'),max=Math.max(1,...src.map(s=>Number(s.live_hours||0)));$('sourceBars').innerHTML=src.length?src.map(s=>`<div class="cf-bar-line"><span>${esc(s.source_name)}</span><div class="cf-bar-track"><div class="cf-bar-fill" style="width:${Math.max(2,Number(s.live_hours||0)/max*100)}%"></div></div><strong>${fmt(s.live_hours)}h</strong></div>`).join(''):empty('No local project data has been registered yet. Open data can still bootstrap ASR.')}

function renderOpenConnectors(){const el=$('openConnectorRows');const rows=state.open_connectors||[];if(!rows.length){el.innerHTML=empty('No open-data connectors registered.');return}el.innerHTML=rows.map(c=>{const connected=Boolean(c.source_id);const gated=c.gated;return `<article class="cf-connector-card"><div class="cf-connector-top"><span class="cf-provider">${esc(c.provider)}</span><span class="rights ${statusClass(c.status)}">${esc(c.status)}</span></div><h3>${esc(c.display_name)}</h3><p>${esc(c.dataset_ref)}${c.dataset_config?` · ${esc(c.dataset_config)}`:''}</p><div class="cf-connector-meta"><span><b>Language</b>${esc(c.language||'—')}</span><span><b>License</b>${esc(c.license_spdx||'Review required')}</span><span><b>Revision</b>${esc((c.dataset_revision||'resolve on worker').slice(0,14))}</span><span><b>Access</b>${gated?'Gated · '+esc(c.token_env_name||'token required'):'Open'}</span></div>${gated?'<div class="cf-note">Accept the provider terms first. The Hugging Face token stays on the GPU worker and is never stored in this page.</div>':''}<div class="cf-connector-actions">${c.source_url?`<a class="cf-btn ghost" target="_blank" rel="noopener" href="${esc(c.source_url)}">View source</a>`:''}${connected?'<span class="cf-connected">✓ Training source connected</span>':`<button class="cf-btn primary connect-open" data-id="${c.id}" type="button">Connect to training pool</button>`}</div></article>`}).join('');document.querySelectorAll('.connect-open').forEach(b=>b.onclick=()=>connectOpen(b.dataset.id))}
async function connectOpen(id){const {error}=await db.rpc('coreforge_connect_open_connector',{p_connector_id:id});if(error){toast(error.message,true);return}toast('Open dataset connected to the training-rights registry.');await load()}

function renderSources(){const rows=$('sourceRows');if(!state.sources?.length){rows.innerHTML='<tr><td colspan="6">No CoreForge sources registered.</td></tr>';return}rows.innerHTML=state.sources.map(s=>`<tr><td><strong>${esc(s.source_name)}</strong><small>${esc(s.source_kind)}${s.project_id?' · project '+s.project_id:''}</small></td><td>${esc(s.language||'—')}</td><td>${s.source_kind==='open_dataset'?'<strong>Remote stream</strong><small>Exact inventory materializes on worker</small>':`<strong>${fmt(s.live_item_count)} items</strong><small>${fmt(s.live_hours)} hours · ${fmt(s.transcript_segments)} segments</small>`}</td><td>${s.source_kind==='open_dataset'?'—':fmt(s.reviewed_items)+' items'}</td><td><span class="rights ${esc(s.rights_status)}">${esc(rightsLabel(s.rights_status))}</span>${s.rights_basis?`<small>${esc(s.rights_basis)}</small>`:''}</td><td>${s.source_kind==='open_dataset'?'—':`<button class="cf-btn ghost edit-source" data-id="${s.id}" type="button">Edit</button>`}</td></tr>`).join('');document.querySelectorAll('.edit-source').forEach(b=>b.onclick=()=>editSource(b.dataset.id))}
function renderDatasets(){const rows=$('datasetRows');if(!state.datasets?.length){rows.innerHTML='<tr><td colspan="8">No datasets yet.</td></tr>';return}rows.innerHTML=state.datasets.map(d=>`<tr><td><strong>${esc(d.name)}</strong><small>v${d.version} · ${date(d.created_at)}</small></td><td>${esc(taskLabel(d.task))}</td><td>${esc(d.language||'—')}</td><td>${fmt(d.item_count)}</td><td>${fmt(d.total_hours)}</td><td><span class="rights ${statusClass(d.manifest_status)}">${esc(d.manifest_status||'complete')}</span></td><td><span class="rights ${d.status==='frozen'?'adatacore_trainable':'unknown'}">${esc(d.status)}</span></td><td>${d.status==='draft'?`<button class="cf-btn primary freeze-dataset" data-id="${d.id}" type="button">Freeze</button>`:'—'}</td></tr>`).join('');document.querySelectorAll('.freeze-dataset').forEach(b=>b.onclick=()=>freezeDataset(b.dataset.id))}
function renderBenchmarks(){const el=$('benchmarkRows');el.innerHTML=state.benchmarks?.length?state.benchmarks.map(b=>`<article class="cf-list-card"><div><strong>${esc(b.name)} · v${b.version}</strong><p>${esc(taskLabel(b.task))} · ${esc(b.language||'all')} · ${fmt(b.item_count)} items · ${fmt(b.total_hours)}h</p></div><span class="rights ${b.status==='frozen'?'adatacore_trainable':'unknown'}">${esc(b.status)}</span></article>`).join(''):empty('No benchmark yet. Create a held-out evaluation dataset before production decisions.')}
function renderRuns(){const el=$('runRows');el.innerHTML=state.training_runs?.length?state.training_runs.map(r=>{const active=['preparing','training','evaluating'].includes(r.status);return `<article class="cf-list-card cf-run-card"><div class="cf-run-main"><div class="cf-run-title"><strong>${esc(r.run_code)} · ${esc(r.name)}</strong><span class="rights ${statusClass(r.status)}">${esc(r.status)}</span></div><p>${esc(taskLabel(r.task))} · ${esc(r.language||'—')} · base: ${esc(r.base_model||'not specified')} · ${esc(r.compute_type)}${r.worker_name?' · '+esc(r.worker_name):''}</p>${active||Number(r.progress)>0?`<div class="cf-progress"><i style="width:${Math.max(0,Math.min(100,Number(r.progress||0)))}%"></i></div><small>${fmt(r.progress)}% · ${esc(r.stage||r.status)}${r.worker_message?' · '+esc(r.worker_message):''}${r.heartbeat_at?' · heartbeat '+esc(ago(r.heartbeat_at)):''}</small>`:''}${r.status==='failed'&&r.error_message?`<small class="cf-error-text">${esc(r.error_message)}</small>`:''}${r.status==='completed'&&r.metrics?`<small>WER ${r.metrics.wer!=null?fmt(Number(r.metrics.wer)*100)+'%':'—'} · CER ${r.metrics.cer!=null?fmt(Number(r.metrics.cer)*100)+'%':'—'}</small>`:''}</div></article>`}).join(''):empty('No training runs.')}
function renderModels(){const el=$('modelRows');el.innerHTML=state.models?.length?state.models.map(m=>`<article class="cf-list-card"><div><strong>${esc(m.name)} ${esc(m.version)}</strong><p>${esc(taskLabel(m.task))} · ${esc(m.language||'—')} · ${esc(m.base_model||'base model not recorded')} · ${esc(m.artifact_uri||'artifact not registered')}</p>${m.metrics?.wer!=null?`<small>WER ${fmt(Number(m.metrics.wer)*100)}% · CER ${m.metrics.cer!=null?fmt(Number(m.metrics.cer)*100)+'%':'—'}</small>`:''}</div><span class="rights ${statusClass(m.status)}">${esc(m.status)}</span></article>`).join(''):empty('No models registered. Successful worker runs will appear here automatically as candidates.')}
function renderWorkers(){const el=$('workerRows');const rows=state.workers||[];if(!rows.length){el.innerHTML=empty('No worker keys yet. Create one, then run workers/coreforge_worker.py on a GPU machine.');return}el.innerHTML=rows.map(w=>{const recent=w.last_seen_at&&(Date.now()-new Date(w.last_seen_at).getTime()<5*60*1000);const shown=w.status==='revoked'?'revoked':recent?(w.status==='busy'?'busy':'online'):'offline';return `<article class="cf-list-card"><div><strong>${esc(w.name)}</strong><p>${shown==='offline'?'Not currently connected':'Last heartbeat '+esc(ago(w.last_seen_at))}${w.capabilities?.gpu?' · '+esc(w.capabilities.gpu):''}</p><small>${w.capabilities?.worker_version?'Worker '+esc(w.capabilities.worker_version):'Token created '+esc(date(w.created_at))}</small></div><div class="cf-row-actions"><span class="rights ${statusClass(shown)}">${esc(shown)}</span>${shown!=='revoked'?`<button class="cf-btn ghost revoke-worker" data-id="${w.id}" type="button">Revoke</button>`:''}</div></article>`}).join('');document.querySelectorAll('.revoke-worker').forEach(b=>b.onclick=()=>revokeWorker(b.dataset.id))}
function renderPolicies(){const el=$('policyRows');const rows=state.auto_policies||[];el.innerHTML=rows.length?rows.map(p=>`<article class="cf-list-card cf-policy"><div><strong>${esc(p.name)}</strong><p>${esc(taskLabel(p.task))} · ${esc(p.language||'all')} · ${esc(p.base_model)}</p><small>Open-data target ${fmt(p.target_open_hours)}h · new local-data threshold ${fmt(p.min_new_local_hours)}h · minimum ${fmt(p.min_days_between)} days between candidates</small></div><button class="cf-toggle ${p.enabled?'on':''} policy-toggle" data-id="${p.id}" data-enabled="${p.enabled?'1':'0'}" type="button" aria-label="Toggle automation"><i></i><span>${p.enabled?'Enabled':'Paused'}</span></button></article>`).join(''):empty('No automation policy has been configured.');document.querySelectorAll('.policy-toggle').forEach(b=>b.onclick=()=>togglePolicy(b.dataset.id,b.dataset.enabled!=='1'))}

function populateForms(){const projects=state.projects||[];$('sourceProject').innerHTML='<option value="">Manual / other source</option>'+projects.map(p=>`<option value="${p.id}">${esc(p.project_name)} · ${fmt(p.audio_hours)}h</option>`).join('');const trainable=state.sources.filter(s=>s.rights_status==='adatacore_trainable');$('datasetSources').innerHTML=trainable.length?trainable.map(s=>`<div class="cf-source-option"><label><input type="checkbox" value="${s.id}"> ${esc(s.source_name)}</label><span>${s.source_kind==='open_dataset'?'OPEN':fmt(s.live_hours)+'h'}</span></div>`).join(''):empty('No sources are marked Adatacore trainable yet.');const frozen=state.datasets.filter(d=>d.status==='frozen');const dsOpts=frozen.map(d=>`<option value="${d.id}">${esc(d.name)} v${d.version} · ${fmt(d.total_hours)}h</option>`).join('');$('benchmarkDataset').innerHTML='<option value="">Independent / manual benchmark</option>'+dsOpts;$('runDataset').innerHTML=dsOpts||'<option value="">No frozen dataset available</option>';$('modelDataset').innerHTML='<option value="">None</option>'+state.datasets.map(d=>`<option value="${d.id}">${esc(d.name)} v${d.version}</option>`).join('');$('modelRun').innerHTML='<option value="">None</option>'+state.training_runs.map(r=>`<option value="${r.id}">${esc(r.run_code)} · ${esc(r.name)}</option>`).join('');$('modelBenchmark').innerHTML='<option value="">None</option>'+state.benchmarks.map(b=>`<option value="${b.id}">${esc(b.name)} v${b.version}</option>`).join('')}
function editSource(id){const s=state.sources.find(x=>x.id===id);if(!s)return;$('sourceId').value=s.id;$('sourceProject').value=s.project_id||'';$('sourceName').value=s.source_name||'';$('sourceLanguage').value=s.language||'';$('sourceKind').value=s.source_kind||'transcription_project';$('sourceRights').value=s.rights_status||'unknown';$('sourceBasis').value=s.rights_basis||'';$('sourceNotes').value=s.rights_notes||'';$('sourceDialog').showModal()}
async function freezeDataset(id){if(!confirm('Freeze this dataset? Local items and open-data connector lineage will be locked for this version.'))return;const {data,error}=await db.rpc('coreforge_freeze_dataset',{p_dataset_id:id});if(error||!data){toast(error?.message||'Dataset could not be frozen.',true);return}toast('Dataset frozen. Open-data manifest will materialize on the worker.');await load()}
async function revokeWorker(id){if(!confirm('Revoke this worker token? The worker will no longer be able to claim or report jobs.'))return;const {error}=await db.rpc('coreforge_revoke_worker',{p_worker_id:id});if(error){toast(error.message,true);return}toast('Worker revoked.');await load()}
async function togglePolicy(id,enabled){const {error}=await db.rpc('coreforge_set_auto_policy',{p_policy_id:id,p_enabled:enabled,p_target_open_hours:null,p_min_new_local_hours:null,p_min_days_between:null});if(error){toast(error.message,true);return}toast(enabled?'Automation enabled.':'Automation paused.');await load()}

function bindForms(){
$('sourceProject').addEventListener('change',()=>{const p=state.projects.find(x=>String(x.id)===$('sourceProject').value);if(p){$('sourceName').value=p.project_name;$('sourceLanguage').value=p.transcription_language||'';$('sourceKind').value='transcription_project'}});
$('sourceForm').addEventListener('submit',async e=>{e.preventDefault();const args={p_id:$('sourceId').value||null,p_source_kind:$('sourceKind').value,p_project_id:$('sourceProject').value?Number($('sourceProject').value):null,p_source_name:$('sourceName').value.trim(),p_language:$('sourceLanguage').value.trim(),p_modality:'speech',p_rights_status:$('sourceRights').value,p_rights_basis:$('sourceBasis').value.trim(),p_rights_notes:$('sourceNotes').value.trim()};const {error}=await db.rpc('coreforge_save_source',args);if(error){toast(error.message,true);return}$('sourceDialog').close('saved');$('sourceForm').reset();$('sourceId').value='';toast('Training source saved.');await load()});
$('datasetForm').addEventListener('submit',async e=>{e.preventDefault();const ids=[...document.querySelectorAll('#datasetSources input:checked')].map(x=>x.value);if(!ids.length){toast('Select at least one trainable source.',true);return}const criteria={reviewed_only:$('datasetReviewedOnly').checked,external_target_hours:Number($('datasetTargetHours').value||20),speaker_safe_split:true,train_pct:90,validation_pct:5,test_pct:5};const {error}=await db.rpc('coreforge_create_dataset',{p_name:$('datasetName').value.trim(),p_task:$('datasetTask').value,p_language:$('datasetLanguage').value.trim(),p_source_ids:ids,p_criteria:criteria});if(error){toast(error.message,true);return}$('datasetDialog').close('saved');$('datasetForm').reset();$('datasetTargetHours').value='20';toast('Dataset draft created. Freeze it when the source mix is final.');await load()});
$('benchmarkForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await db.rpc('coreforge_create_benchmark',{p_name:$('benchmarkName').value.trim(),p_task:$('benchmarkTask').value,p_language:$('benchmarkLanguage').value.trim(),p_dataset_id:$('benchmarkDataset').value||null,p_notes:$('benchmarkNotes').value.trim()});if(error){toast(error.message,true);return}$('benchmarkDialog').close('saved');$('benchmarkForm').reset();toast('Benchmark registered.');await load()});
$('runForm').addEventListener('submit',async e=>{e.preventDefault();const ds=state.datasets.find(x=>x.id===$('runDataset').value),version='v'+(state.training_runs.filter(r=>r.task===$('runTask').value&&r.language===$('runLanguage').value.trim()).length+1);const target=Number(ds?.criteria?.external_target_hours||20);const config={dataset_version:ds?.version||null,target_hours:target,model_name:$('runTask').value==='asr'?'Adatacore Hindi Speech':'Adatacore Model',model_version:version,epochs:3,learning_rate:0.00001,train_pct:90,validation_pct:5,test_pct:5,speaker_safe_split:true};const {error}=await db.rpc('coreforge_create_training_run',{p_name:$('runName').value.trim(),p_task:$('runTask').value,p_language:$('runLanguage').value.trim(),p_dataset_id:$('runDataset').value||null,p_base_model:$('runBaseModel').value.trim(),p_compute_type:$('runCompute').value,p_config:config});if(error){toast(error.message,true);return}$('runDialog').close('saved');$('runForm').reset();$('runBaseModel').value='openai/whisper-small';$('runLanguage').value='hi';toast('Training run queued. A connected worker can claim it without this page staying open.');await load()});
$('modelForm').addEventListener('submit',async e=>{e.preventDefault();let metrics={};try{metrics=$('modelMetrics').value.trim()?JSON.parse($('modelMetrics').value):{}}catch(_){toast('Metrics must be valid JSON.',true);return}const {error}=await db.rpc('coreforge_register_model',{p_name:$('modelName').value.trim(),p_task:$('modelTask').value,p_language:$('modelLanguage').value.trim(),p_version:$('modelVersion').value.trim(),p_training_run_id:$('modelRun').value||null,p_dataset_id:$('modelDataset').value||null,p_benchmark_id:$('modelBenchmark').value||null,p_base_model:$('modelBaseModel').value.trim(),p_metrics:metrics,p_notes:$('modelNotes').value.trim()});if(error){toast(error.message,true);return}$('modelDialog').close('saved');$('modelForm').reset();toast('Model candidate registered.');await load()});
$('workerForm').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await db.rpc('coreforge_create_worker_key',{p_name:$('workerName').value.trim(),p_capabilities:{tasks:['asr']}});if(error||!data?.token){toast(error?.message||'Worker key could not be created.',true);return}$('workerDialog').close('saved');$('workerForm').reset();$('workerTokenValue').textContent=data.token;$('workerTokenDialog').showModal();await load()});
$('copyWorkerToken').onclick=async()=>{try{await navigator.clipboard.writeText($('workerTokenValue').textContent);toast('Worker token copied.')}catch{toast('Copy failed. Select the token manually.',true)}};$('closeWorkerToken').onclick=()=>$('workerTokenDialog').close('done');}

window.addEventListener('DOMContentLoaded',async()=>{bindTabs();bindDialogs();bindForms();$('refreshCoreForge').onclick=load;try{if(await guard())await load()}catch(error){toast(error.message||'CoreForge failed to initialize.',true)}});
})();