(()=>{'use strict';if(window.__adatacorePlatformTheme)return;window.__adatacorePlatformTheme=true;
const KEY='adatacore-theme',LEGACY=['adatacore-dashboard-theme','adatacore-admin-theme'];
const valid=v=>v==='dark'||v==='light';
function read(){try{const own=localStorage.getItem(KEY);if(valid(own))return own;for(const k of LEGACY){const v=localStorage.getItem(k);if(valid(v))return v}}catch(_){}return window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
function apply(v,persist=false){const t=valid(v)?v:'light',root=document.documentElement;root.dataset.adatacoreTheme=t;root.dataset.dashboardTheme=t;root.dataset.adminTheme=t;root.style.colorScheme=t;if(persist)try{localStorage.setItem(KEY,t);LEGACY.forEach(k=>localStorage.setItem(k,t))}catch(_){}document.querySelectorAll('[data-platform-theme-toggle]').forEach(b=>{b.dataset.theme=t;b.setAttribute('aria-pressed',String(t==='dark'));const i=b.querySelector('.pt-icon');if(i)i.textContent=t==='dark'?'☀':'☾';const l=b.querySelector('.pt-label');if(l)l.textContent=t==='dark'?'Light':'Dark'});const wi=document.getElementById('themeIcon'),wl=document.getElementById('themeLabel');if(wi)wi.textContent=t==='dark'?'☀':'☾';if(wl)wl.textContent=t==='dark'?'Light mode':'Dark mode'}
apply(read(),false);
function toggle(){const next=document.documentElement.dataset.adatacoreTheme==='dark'?'light':'dark';if(document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.startViewTransition(()=>apply(next,true))}else apply(next,true)}
function mount(){const existing=document.getElementById('themeToggle');if(existing){existing.addEventListener('click',()=>setTimeout(()=>{const v=document.documentElement.dataset.dashboardTheme||document.documentElement.dataset.adminTheme||read();apply(v,true)},0));return}
if(document.querySelector('[data-platform-theme-toggle]'))return;const b=document.createElement('button');b.type='button';b.className='platform-theme-toggle';b.dataset.platformThemeToggle='1';b.innerHTML='<span class="pt-icon" aria-hidden="true"></span><span class="pt-label"></span>';b.addEventListener('click',toggle);const host=document.querySelector('.admin-header-actions,.page-header,.apps-top,.top,.header-actions,.toolbar-actions');if(host){host.appendChild(b)}else{b.classList.add('platform-theme-floating');document.body.appendChild(b)}apply(read(),false)}
function animateHash(){const id=(location.hash||'').slice(1);if(!id)return;requestAnimationFrame(()=>{const el=document.getElementById('view-'+id)||document.querySelector('.workspace-view.active');if(!el)return;el.classList.remove('platform-view-enter');void el.offsetWidth;el.classList.add('platform-view-enter');setTimeout(()=>el.classList.remove('platform-view-enter'),220)})}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.target||a.hasAttribute('download')||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;let u;try{u=new URL(a.href,location.href)}catch(_){return}if(u.origin!==location.origin)return;if(u.pathname===location.pathname&&u.search===location.search&&u.hash){setTimeout(animateHash,0);return}if(u.pathname!==location.pathname&&!matchMedia('(prefers-reduced-motion: reduce)').matches){e.preventDefault();document.documentElement.classList.add('platform-page-leaving');setTimeout(()=>location.href=u.href,105)}},true);
window.addEventListener('hashchange',animateHash);window.addEventListener('pageshow',()=>document.documentElement.classList.remove('platform-page-leaving'));window.addEventListener('storage',e=>{if(e.key===KEY&&valid(e.newValue))apply(e.newValue,false)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();document.documentElement.classList.add('platform-page-ready');animateHash()},{once:true});else{mount();document.documentElement.classList.add('platform-page-ready');animateHash()}
})();
