(()=>{'use strict';
const $=id=>document.getElementById(id),db=supabase.createClient('https://llmhyezgcnbognmmsnzq.supabase.co','sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let projectId=Number(new URLSearchParams(location.search).get('project'))||null,lab={projects:[],items:[],people:[]},selected=new Set(),sources=[],sourceSelected=new Set(),uploading=false,loadGeneration=0;
const fmt=n=>`${Math.floor((n||0)/60)}:${String(Math.floor(n||0)%60).padStart(2,'0')}`;
function notice(message,error=false){$('notice').textContent=message;$('notice').className='notice '+(error?'error':'success')}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw Error(error.message);return data}
async function action(button,messageNode,fn){button.disabled=true;if(messageNode)messageNode.textContent='Working…';try{await fn()}catch(e){if(messageNode)messageNode.textContent=e.message;else notice(e.message,true)}finally{button.disabled=false}}
async function load(){const generation=++loadGeneration,requested=projectId;['importExisting','uploadExternal','assign'].forEach(id=>$(id).disabled=true);let next=await rpc('tx_get_lab',{p_project_id:requested}),nextId=requested;if(!next.projects.some(p=>p.id===nextId)&&next.projects.length){nextId=next.projects[0].id;next=await rpc('tx_get_lab',{p_project_id:nextId})}if(generation!==loadGeneration)return;lab=next;projectId=nextId;if(projectId)history.replaceState(null,'',`/admin/transcription?project=${projectId}`);render()}
function filtered(){const q=$('search').value.toLowerCase(),status=$('statusFilter').value;return lab.items.filter(a=>(!status||a.status===status)&&[a.display_name,a.source_project_title,a.source_folder,a.assignee,a.reviewer].some(v=>String(v||'').toLowerCase().includes(q)))}
function render(){const p=lab.projects.find(p=>p.id===projectId);$('projectList').innerHTML=lab.projects.map(p=>`<button class="project-option ${p.id===projectId?'active':''}" data-project="${p.id}">${esc(p.name)}<small>${p.count} modules · ${esc(p.status)}</small></button>`).join('')||'<div class="empty">Create your first project.</div>';$('projectName').textContent=p?.name||'Create a transcription project';$('projectDescription').textContent=p?.description||'';$('settingsLink').classList.toggle('hidden',!p);$('settingsLink').href=`/admin/project-lab?project=${projectId}`;['importExisting','uploadExternal','assign'].forEach(id=>$(id).disabled=!p);$('totalCount').textContent=lab.items.length;$('readyCount').textContent=lab.items.filter(a=>a.status==='unassigned'||a.task_status==='cancelled').length;$('workingCount').textContent=lab.items.filter(a=>['assigned','in_progress','in_review','changes_requested'].includes(a.status)).length;$('reviewedCount').textContent=lab.items.filter(a=>['approved','reviewed'].includes(a.status)).length;$('personPicker').innerHTML='<option value="">Choose a participant…</option>'+lab.people.map(u=>`<option value="${esc(u.email)}">${esc(u.name||u.email)} · ${esc(u.uid||u.email)}</option>`).join('');renderRows()}
function renderRows(){const rows=filtered();$('audioRows').innerHTML=rows.map(a=>`<tr><td><input type="checkbox" data-item="${a.id}" aria-label="Select ${esc(a.display_name||'audio')}" ${selected.has(a.id)?'checked':''}></td><td><strong>${esc(a.display_name||a.recording_path.split('/').pop())}</strong><small>${esc(a.source_project_title)} / ${esc(a.source_folder||'Root')}</small></td><td>${a.duration_seconds?fmt(a.duration_seconds):'On open'}</td><td><span class="pill ${a.status==='approved'?'green':a.status.includes('review')?'purple':''}">${esc(a.status.replaceAll('_',' '))}</span></td><td>${esc(a.assignee||'Unassigned')}${a.reviewer?`<small>Audit: ${esc(a.reviewer)}</small>`:''}</td><td><a class="button" href="/transcription?item=${a.id}">${a.status==='submitted'||a.status==='in_review'?'Audit':'Open'} ↗</a></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No audio modules here yet.<br>Import recordings or upload audio to get started.</td></tr>';$('selectionCount').textContent=`${selected.size} selected`;$('selectAll').checked=rows.length>0&&rows.every(a=>selected.has(a.id))}
$('projectList').onclick=e=>{const b=e.target.closest('[data-project]');if(b){projectId=Number(b.dataset.project);selected.clear();load().catch(e=>notice(e.message,true))}};
$('audioRows').onchange=e=>{const id=e.target.dataset.item;if(id){e.target.checked?selected.add(id):selected.delete(id);$('selectionCount').textContent=`${selected.size} selected`}};
$('selectAll').onchange=e=>{filtered().forEach(a=>e.target.checked?selected.add(a.id):selected.delete(a.id));renderRows()};$('search').oninput=$('statusFilter').onchange=renderRows;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(uploading&&b.closest('dialog').id==='uploadDialog')return;b.closest('dialog').close()});
$('newProject').onclick=()=>$('projectDialog').showModal();$('projectConfirm').onclick=()=>action($('projectConfirm'),$('projectMessage'),async()=>{projectId=await rpc('tx_create_project',{p_name:$('newName').value,p_description:$('newDescription').value});$('projectDialog').close();selected.clear();await load();notice('Transcription project created.')});
function shownSources(){return sources.filter(s=>(!$('sourceProject').value||s.project===$('sourceProject').value)&&(!$('sourceFolder').value||s.folder===$('sourceFolder').value))}
function sourceFolders(){const rows=sources.filter(s=>!$('sourceProject').value||s.project===$('sourceProject').value);$('sourceFolder').innerHTML='<option value="">All folders</option>'+[...new Set(rows.map(s=>s.folder))].sort().map(v=>`<option>${esc(v)}</option>`).join('');renderSources()}
function renderSources(){$('sourceRows').innerHTML=shownSources().map(s=>`<label class="source-row"><input type="checkbox" data-source="${s.key}" ${sourceSelected.has(s.key)?'checked':''}><span>${esc(s.name)}<small>${esc(s.project)} / ${esc(s.folder)} · ${s.duration_seconds?fmt(s.duration_seconds):'Duration detected on open'}</small></span></label>`).join('')||'<div class="empty">No recordings match this source.</div>';$('sourceCount').textContent=`${sourceSelected.size} selected · ${shownSources().length} shown`}
$('importExisting').onclick=()=>action($('importExisting'),null,async()=>{$('sourceMessage').textContent='';sourceSelected.clear();sources=await rpc('tx_audio_sources');$('sourceProject').innerHTML='<option value="">All projects</option>'+[...new Set(sources.map(s=>s.project))].sort().map(v=>`<option>${esc(v)}</option>`).join('');sourceFolders();$('sourceDialog').showModal()});
$('sourceProject').onchange=sourceFolders;$('sourceFolder').onchange=renderSources;$('sourceRows').onchange=e=>{if(e.target.dataset.source){e.target.checked?sourceSelected.add(e.target.dataset.source):sourceSelected.delete(e.target.dataset.source);$('sourceCount').textContent=`${sourceSelected.size} selected · ${shownSources().length} shown`}};$('sourceSelectAll').onclick=()=>{shownSources().forEach(s=>sourceSelected.add(s.key));renderSources()};
$('importConfirm').onclick=()=>action($('importConfirm'),$('sourceMessage'),async()=>{if(!sourceSelected.size)throw Error('Select at least one recording.');const r=await rpc('tx_import_sources',{p_project_id:projectId,p_sources:sources.filter(s=>sourceSelected.has(s.key)).map(s=>({bucket:s.bucket,path:s.path}))});$('sourceDialog').close();await load();notice(`${r.imported} audio modules imported${r.duplicates?`; ${r.duplicates} already in this project`:''}.`)});
$('uploadExternal').onclick=()=>{$('uploadResults').textContent='';$('uploadDialog').showModal()};
function duration(file){return new Promise((resolve,reject)=>{const a=new Audio(),url=URL.createObjectURL(file),finish=(fn,value)=>{clearTimeout(timer);a.removeAttribute('src');a.load();URL.revokeObjectURL(url);fn(value)},timer=setTimeout(()=>finish(reject,Error('Could not read duration; convert this file to WAV or MP3.')),15000);a.preload='metadata';a.onloadedmetadata=()=>{if(Number.isFinite(a.duration)&&a.duration>0)finish(resolve,Math.round(a.duration*1000));else{const ctx=new AudioContext();file.arrayBuffer().then(b=>ctx.decodeAudioData(b)).then(b=>finish(resolve,Math.round(b.duration*1000))).catch(()=>finish(reject,Error('Unsupported audio file.'))).finally(()=>ctx.close())}};a.onerror=()=>finish(reject,Error('This browser cannot read this audio format.'));a.src=url})}
$('uploadConfirm').onclick=()=>action($('uploadConfirm'),null,async()=>{const files=[...$('audioFiles').files];if(!files.length)throw Error('Choose audio files first.');uploading=true;$('audioFiles').disabled=true;let successes=0;try{for(const file of files){const line=document.createElement('div');line.className='file-result';line.textContent=`${file.name} — checking…`;$('uploadResults').append(line);let path=null;try{if(file.size>52428800||!file.size)throw Error('File must be between 1 byte and 50 MB.');const ext=file.name.split('.').pop().toLowerCase();if(!['mp3','wav','m4a','webm','ogg','flac','aac','mp4'].includes(ext))throw Error('Unsupported audio extension.');const ms=await duration(file);if(ms>14400000)throw Error('Audio must be under 4 hours.');path=`${projectId}/${crypto.randomUUID()}.${ext}`;line.textContent=`${file.name} — uploading…`;const mime={mp3:'audio/mpeg',wav:'audio/wav',m4a:'audio/mp4',webm:'audio/webm',ogg:'audio/ogg',flac:'audio/flac',aac:'audio/aac',mp4:'audio/mp4'}[ext];const {error}=await db.storage.from('transcription_audio').upload(path,file,{contentType:mime,upsert:false});if(error)throw error;await rpc('tx_register_upload',{p_project_id:projectId,p_path:path,p_name:file.name,p_folder:$('uploadFolder').value,p_duration_ms:ms});line.textContent=`${file.name} — ready · ${fmt(ms/1000)}`;successes++}catch(e){line.textContent=`${file.name} — ${e.message}`;line.style.color='#b33945';if(path)await db.storage.from('transcription_audio').remove([path]);}}}finally{uploading=false;$('audioFiles').disabled=false;$('audioFiles').value='';await load();notice(`${successes} of ${files.length} audio modules added.`,successes!==files.length)}});
$('assign').onclick=()=>{$('assignScope').textContent=selected.size?`Assign from ${selected.size} selected modules.`:'Assign the next eligible modules from this project.';$('assignMessage').textContent='';$('assignDialog').showModal()};$('personPicker').onchange=e=>{if(e.target.value)$('assignPeople').value+=($('assignPeople').value.trim()?'\n':'')+e.target.value;e.target.value=''};
$('assignConfirm').onclick=()=>action($('assignConfirm'),$('assignMessage'),async()=>{const keys=[...new Set($('assignPeople').value.split(/[\s,;]+/).map(x=>x.trim()).filter(Boolean))],qty=Number($('assignQty').value);if(!keys.length||!Number.isInteger(qty)||qty<1||qty>100)throw Error('Add participants and a whole-number quantity from 1 to 100.');const r=await rpc('tx_assign',{p_project_id:projectId,p_user_keys:keys,p_layer:$('assignLayer').value,p_quantity:qty,p_item_ids:selected.size?[...selected]:null});$('assignDialog').close();selected.clear();await load();notice(`${r.created} modules assigned. Participants can open them from their workspace.`)});
window.addEventListener('beforeunload',e=>{if(uploading){e.preventDefault();e.returnValue=''}});
(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return}await load()})().catch(e=>notice(e.message,true));
})();
