(()=>{'use strict';
const $=id=>document.getElementById(id),M=TranscriptionModel,db=supabase.createClient('https://llmhyezgcnbognmmsnzq.supabase.co','sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml'),itemId=new URLSearchParams(location.search).get('item'),audio=$('audio'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,segments=[],speakers=[],selected=null,duration=0,buffer=null,ctx=null,mediaSource=null,gains=[],dirty=false,counter=0,saveTimer=null,saving=null,history=[],future=[],stopAt=null,loopStart=null,backupKey='',recovery=null,conflict=false,showOnlyIssues=false,lint=[],waveDrag=null;
let aiInfo=null;
const canEdit=()=>Boolean(data?.editable)&&!conflict;
function notice(text,error=false){$('notice').textContent=text;$('notice').className='notice '+(error?'error':'')}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),3500)}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw Error(error.message);return data}
function snapshot(){return structuredClone({segments,speakers})}
function checkpoint(){history.push(snapshot());if(history.length>60)history.shift();future=[];buttons()}
function setSnapshot(s){segments=structuredClone(s.segments);speakers=structuredClone(s.speakers);if(!segments.some(s=>s.id===selected))selected=null;changed();renderAll()}
function backup(){if(!backupKey)return;try{localStorage.setItem(backupKey,JSON.stringify({revision:data.item.revision,segments,speakers,duration_ms:duration,dirty,at:Date.now()}))}catch(_){}}
function changed(){dirty=true;counter++;backup();$('saveState').textContent='Unsaved changes';clearTimeout(saveTimer);if(!conflict)saveTimer=setTimeout(()=>save().catch(e=>notice(e.message,true)),1800);updateLint();buttons()}
function buttons(){const edit=canEdit();['save','addSegment','importTranscript','addSpeaker'].forEach(id=>$(id).disabled=!edit||!duration);$('undo').disabled=!edit||!history.length;$('redo').disabled=!edit||!future.length;$('submit').disabled=!edit||!duration;$('save').textContent=saving?'Saving…':'Save draft';$('submit').textContent=data?.mode==='reviewer'||(data?.mode==='admin'&&['submitted','in_review'].includes(data?.item.status))?'Submit review':'Submit transcript';$('aiOriginal').disabled=!data;$('useAIDraft').disabled=!canUseAI();$('exportAI').disabled=!aiInfo?.draft}
function canUseAI(){return canEdit()&&duration>0&&aiInfo?.draft&&segments.length===0&&!dirty&&!saving&&data.mode!=='reviewer'&&!['submitted','in_review','approved','reviewed'].includes(data.item.status)}
async function loadAI(){aiInfo=await rpc('tx_ai_item',{p_item:itemId});const latest=aiInfo?.latest,draft=aiInfo?.draft;$('aiDraftNote').textContent=draft?'AI-assisted draft · Verify every segment against the audio. Human edits are saved separately.':latest?.status==='failed'?'AI draft unavailable: '+latest.error_message:latest&&['queued','dispatched','running'].includes(latest.status)?'AI draft is being prepared. Existing edits will not be overwritten.':'No AI draft yet. An administrator can generate one from Transcription Lab.';buttons()}
$('aiOriginal').onclick=async()=>{try{await loadAI();const draft=aiInfo?.draft;if(!draft)return toast('No completed AI draft is available yet.');$('aiOriginalMeta').textContent=`${draft.model} · ${new Date(draft.finished_at).toLocaleString()} · Read-only reference`;$('aiOriginalRows').innerHTML=draft.segments.map(s=>`<div class="ai-reference-row"><button data-ai-play="${s.id}" aria-label="Play AI segment">▶</button><div><small>${esc(draft.speakers.find(p=>p.id===s.speaker_id)?.label||s.speaker_id)} · ${M.time(s.start_ms)}–${M.time(s.end_ms)}</small><p>${esc(s.transcript)}</p></div></div>`).join('');$('aiOriginalDialog').showModal()}catch(e){notice('Could not load AI reference: '+e.message,true)}};
$('aiOriginalRows').onclick=e=>{const id=e.target.closest('[data-ai-play]')?.dataset.aiPlay,s=aiInfo?.draft?.segments.find(s=>s.id===id);if(s)playSegment(s)};
$('useAIDraft').onclick=()=>{if(!canUseAI())return toast('AI can only fill an empty, saved transcript. Your edits were not changed.');checkpoint();segments=structuredClone(aiInfo.draft.segments);speakers=structuredClone(aiInfo.draft.speakers);changed();renderAll();$('aiOriginalDialog').close();toast('AI draft added. Check every segment before submitting; Undo restores the empty transcript.')};
$('exportAI').onclick=()=>{if(aiInfo?.draft)exportFile(JSON.stringify({schema_version:1,audio_item_id:itemId,ai_job_id:aiInfo.draft.id,model:aiInfo.draft.model,duration_ms:aiInfo.draft.duration_ms,speakers:aiInfo.draft.speakers,segments:aiInfo.draft.segments},null,2),'transcription-ai-original.json','application/json')};
function updateLint(){lint=M.lint(segments,duration,speakers);const errors=lint.reduce((n,x)=>n+x.errors.length,0),warnings=lint.reduce((n,x)=>n+x.warnings.length,0);$('issues').textContent=`${errors} error${errors===1?'':'s'}${warnings?` · ${warnings} warnings`:''}`;$('issues').style.color=errors?'#c33d4b':warnings?'#ab782d':'#33865c';$('segmentCount').textContent=`${segments.length} segment${segments.length===1?'':'s'}`;document.querySelectorAll('[data-segment]').forEach(row=>{const x=lint.find(x=>x.id===row.dataset.segment);if(!x)return;row.classList.toggle('issue',x.errors.length>0);const cell=row.querySelector('.lint-cell');cell.innerHTML=`<span class="lint-dot ${x.errors.length?'error':x.warnings.length?'warning':''}"></span><span class="small">${x.errors.length?'Fix':x.warnings.length?'Check':'OK'}</span><div class="lint-note">${esc([...x.errors,...x.warnings].join(' · '))}</div>`})}
function renderRows(){const filter=$('speakerFilter').value,q=$('textSearch').value.toLowerCase();updateLint();const rows=segments.map((s,i)=>({s,i})).filter(({s})=>(!filter||s.speaker_id===filter)&&(!q||s.transcript.toLowerCase().includes(q))&&(!showOnlyIssues||lint.find(x=>x.id===s.id)?.errors.length||lint.find(x=>x.id===s.id)?.warnings.length));$('segmentRows').innerHTML=rows.map(({s,i})=>{const index=speakers.findIndex(x=>x.id===s.speaker_id),original=data.item.submitted_segments?.find(x=>x.id===s.id),changedOriginal=original&&(original.transcript!==s.transcript||original.start_ms!==s.start_ms||original.end_ms!==s.end_ms||original.speaker_id!==s.speaker_id);return `<tr data-segment="${s.id}" class="${selected===s.id?'selected':''}"><td>${String(i+1).padStart(2,'0')}</td><td><select data-field="speaker_id" aria-label="Speaker for segment ${i+1}" style="color:${M.colors[index%M.colors.length]}" ${canEdit()?'':'disabled'}>${speakers.map(p=>`<option value="${p.id}" ${p.id===s.speaker_id?'selected':''}>${esc(p.label)}</option>`).join('')}</select></td><td><input data-field="start_ms" aria-label="Start time for segment ${i+1}" inputmode="decimal" value="${M.time(s.start_ms)}" ${canEdit()?'':'readonly'}></td><td><input data-field="end_ms" aria-label="End time for segment ${i+1}" inputmode="decimal" value="${M.time(s.end_ms)}" ${canEdit()?'':'readonly'}></td><td><textarea data-field="transcript" aria-label="Transcript for segment ${i+1}" placeholder="Type what you hear…" ${canEdit()?'':'readonly'}>${esc(s.transcript)}</textarea>${$('diffToggle').checked?(original?(changedOriginal?`<div class="diff-original">Submitted · ${M.time(original.start_ms)}–${M.time(original.end_ms)}<br>${esc(original.transcript)}</div>`:''):'<div class="diff-original">Added after the submitted version</div>'):''}</td><td class="lint-cell"></td><td><div class="row-actions"><button data-action="play" title="Play segment" aria-label="Play segment ${i+1}">▶</button><button data-action="split" title="Split at playhead" ${canEdit()?'':'disabled'}>Split</button><button data-action="merge" title="Merge with next segment of the same speaker" ${canEdit()?'':'disabled'}>Merge</button><button data-action="delete" class="danger" aria-label="Delete segment ${i+1}" ${canEdit()?'':'disabled'}>×</button></div></td></tr>`}).join('');const deleted=(data.item.submitted_segments||[]).filter(s=>!segments.some(x=>x.id===s.id));$('deletedDiff').classList.toggle('hidden',!$('diffToggle').checked||!deleted.length);$('deletedDiff').innerHTML=deleted.map(s=>`<div class="diff-original">Removed · ${M.time(s.start_ms)}–${M.time(s.end_ms)}<br>${esc(s.transcript)}</div>`).join('');$('emptySegments').classList.toggle('hidden',rows.length>0);$('emptySegments').textContent=segments.length?'No segments match these filters.':'Drag across a waveform to create your first segment, or use “+ Segment” at the playhead.';updateLint()}
function renderAll(){const selectedFilter=$('speakerFilter').value;$('speakerFilter').innerHTML='<option value="">All speakers</option>'+speakers.map(s=>`<option value="${s.id}">${esc(s.label)}</option>`).join('');$('speakerFilter').value=speakers.some(s=>s.id===selectedFilter)?selectedFilter:'';renderRows();renderWaves();buttons()}
function laneWidth(){return Math.max(300,$('waveScroller').clientWidth-(innerWidth<900?88:126))*Number($('zoom').value)}
function renderWaves(){const width=laneWidth(),label=innerWidth<900?88:126;$('waveContent').style.width=`${width+label}px`;$('waveRuler').innerHTML='';const tick=Math.max(.25,Math.pow(10,Math.floor(Math.log10(Math.max(1,duration/1000/width*90)))));for(let t=0;t<=duration/1000;t+=tick){const mark=document.createElement('span');mark.style.left=`${t*1000/duration*100}%`;mark.textContent=M.time(t*1000,tick<1);$('waveRuler').append(mark)}
 $('lanes').innerHTML=speakers.map((s,i)=>`<div class="speaker-lane" style="--lane:${M.colors[i%M.colors.length]}"><div class="speaker-name"><strong>${esc(s.label)}</strong><small>${buffer?.numberOfChannels===1?'Shared mono':`Channel ${Number(s.channel||0)+1}`}</small></div><div class="lane-wave" data-speaker="${s.id}" tabindex="0" role="img" aria-label="${esc(s.label)} waveform. Drag a range to create a segment."><canvas aria-hidden="true"></canvas><div class="region-layer"></div><div class="playhead"></div></div></div>`).join('');
 document.querySelectorAll('.lane-wave').forEach(lane=>{const s=speakers.find(s=>s.id===lane.dataset.speaker),c=lane.querySelector('canvas');c.width=Math.min(24000,Math.ceil(width*devicePixelRatio));c.height=148*Math.min(devicePixelRatio,2);const g=c.getContext('2d');g.strokeStyle='#8794a2';g.lineWidth=1;g.beginPath();if(buffer){const samples=buffer.getChannelData(Math.min(Number(s.channel||0),buffer.numberOfChannels-1)),step=Math.max(1,Math.floor(samples.length/c.width));for(let x=0;x<c.width;x++){let min=0,max=0;for(let j=x*step;j<Math.min(samples.length,(x+1)*step);j++){min=Math.min(min,samples[j]);max=Math.max(max,samples[j])}g.moveTo(x,c.height/2+min*c.height*.45);g.lineTo(x,c.height/2+max*c.height*.45)}}else{g.moveTo(0,c.height/2);g.lineTo(c.width,c.height/2)}g.stroke()});renderRegions();paintPlayhead()}
function renderRegions(){document.querySelectorAll('.lane-wave').forEach(lane=>{lane.querySelector('.region-layer').innerHTML=segments.filter(s=>s.speaker_id===lane.dataset.speaker).map(s=>`<div class="wave-region ${selected===s.id?'selected':''}" data-region="${s.id}" style="left:${s.start_ms/duration*100}%;width:${Math.max(0,s.end_ms-s.start_ms)/duration*100}%" title="${esc(s.transcript||'Empty segment')}"><span class="region-label">${segments.indexOf(s)+1}</span>${canEdit()?'<span class="handle start" data-edge="start_ms"></span><span class="handle end" data-edge="end_ms"></span>':''}</div>`).join('')})}
function selectSegment(id,scroll=false){selected=id;document.querySelectorAll('[data-segment]').forEach(row=>row.classList.toggle('selected',row.dataset.segment===id));renderRegions();if(scroll)document.querySelector(`[data-segment="${id}"]`)?.scrollIntoView({block:'nearest',behavior:'smooth'})}
function addSegment(start=Math.round(audio.currentTime*1000),end=null,speakerId=null){if(!canEdit()||!duration)return;const sid=speakerId||$('speakerFilter').value||speakers[0].id;start=Math.min(Math.max(0,start),duration-1);const existing=segments.find(s=>s.speaker_id===sid&&start>=s.start_ms&&start<s.end_ms);if(existing&&end===null){selectSegment(existing.id,true);return toast('The playhead is inside an existing segment. Split it or move to a gap.')}const next=segments.filter(s=>s.speaker_id===sid&&s.start_ms>start).sort((a,b)=>a.start_ms-b.start_ms)[0];end=end??Math.min(start+3000,next?.start_ms??duration,duration);if(end<=start)return;checkpoint();const s={id:crypto.randomUUID(),speaker_id:sid,start_ms:Math.round(start),end_ms:Math.round(Math.min(end,duration)),transcript:''};segments.push(s);segments.sort((a,b)=>a.start_ms-b.start_ms||a.end_ms-b.end_ms);selected=s.id;changed();renderAll();document.querySelector(`[data-segment="${s.id}"] textarea`)?.focus()}
function rowAction(id,action){const s=segments.find(s=>s.id===id);if(!s)return;selectSegment(id);if(action==='play')return playSegment(s);if(!canEdit())return;try{if(action==='split'){const updated=M.split(segments,id,Math.round(audio.currentTime*1000),crypto.randomUUID());checkpoint();segments=updated}else if(action==='merge'){const updated=M.merge(segments,id);checkpoint();segments=updated}else if(action==='delete'){checkpoint();segments=segments.filter(s=>s.id!==id);selected=null;toast('Segment removed. Use Undo to restore it.')}changed();renderAll()}catch(e){toast(e.message)}}
$('segmentRows').addEventListener('focusin',e=>{const row=e.target.closest('[data-segment]');if(!row)return;selectSegment(row.dataset.segment);if(canEdit()&&e.target.dataset.field)checkpoint()});
$('segmentRows').addEventListener('input',e=>{const field=e.target.dataset.field,row=e.target.closest('[data-segment]');if(!field||!row||!canEdit())return;const s=segments.find(s=>s.id===row.dataset.segment);if(!s)return;if(field==='start_ms'||field==='end_ms'){const value=M.parseTime(e.target.value);e.target.setCustomValidity(Number.isFinite(value)?'':'Use mm:ss.mmm or seconds');if(!Number.isFinite(value)){e.target.reportValidity();return}s[field]=value}else s[field]=e.target.value;changed();renderRegions()});
$('segmentRows').onclick=e=>{const b=e.target.closest('[data-action]');if(b)rowAction(b.closest('[data-segment]').dataset.segment,b.dataset.action)};
const position=(e,lane)=>Math.round(Math.max(0,Math.min(1,(e.clientX-lane.getBoundingClientRect().left)/lane.getBoundingClientRect().width))*duration);
$('lanes').onpointerdown=e=>{const lane=e.target.closest('.lane-wave');if(!lane||!duration||e.button!==0)return;const region=e.target.closest('[data-region]'),edge=e.target.dataset.edge;waveDrag={lane,start:position(e,lane),clientX:e.clientX,id:region?.dataset.region,edge,moved:false};if(edge&&canEdit())checkpoint();lane.setPointerCapture(e.pointerId);if(region)selectSegment(region.dataset.region)};
$('lanes').onpointermove=e=>{if(!waveDrag)return;const d=waveDrag,at=position(e,d.lane);d.moved=Math.abs(e.clientX-d.clientX)>4;if(d.edge&&canEdit()){const s=segments.find(s=>s.id===d.id);s[d.edge]=d.edge==='start_ms'?Math.min(at,s.end_ms-1):Math.max(at,s.start_ms+1);renderRegions()}else if(!d.id&&d.moved&&canEdit()){let box=d.lane.querySelector('.wave-selection');if(!box){box=document.createElement('div');box.className='wave-selection';d.lane.append(box)}box.style.left=`${Math.min(at,d.start)/duration*100}%`;box.style.width=`${Math.abs(at-d.start)/duration*100}%`}};
$('lanes').onpointerup=e=>{if(!waveDrag)return;const d=waveDrag;waveDrag=null;d.lane.querySelector('.wave-selection')?.remove();const at=position(e,d.lane);if(d.edge&&canEdit()){changed();renderRows();renderRegions()}else if(!d.id&&d.moved&&Math.abs(at-d.start)>30&&canEdit())addSegment(Math.min(at,d.start),Math.max(at,d.start),d.lane.dataset.speaker);else{stopAt=null;audio.currentTime=at/1000;paintPlayhead()}};
$('lanes').onpointercancel=()=>{if(waveDrag?.edge){changed();renderRows()}waveDrag?.lane.querySelector('.wave-selection')?.remove();waveDrag=null};
async function save(){clearTimeout(saveTimer);if([...document.querySelectorAll('#segmentRows input')].some(x=>!x.checkValidity()))throw Error('Fix the invalid time field before saving.');if(saving){await saving;if(dirty)return save();return}if(!dirty)return;if(!canEdit())throw Error('This transcript is read only. Download your local draft if needed.');if(!duration)throw Error('Wait for the audio to finish loading.');const generation=counter,payload=structuredClone({p_item:itemId,p_revision:data.item.revision,p_segments:segments,p_speakers:speakers,p_duration_ms:duration});$('saveState').textContent='Saving…';saving=(async()=>{try{const r=await rpc('tx_save',payload);data.item.revision=r.revision;dirty=counter!==generation;if(dirty){backup();$('saveState').textContent='Unsaved changes'}else{try{localStorage.removeItem(backupKey)}catch(_){}$('saveState').textContent='All changes saved'}}catch(e){$('saveState').textContent='Save failed — draft kept';if(e.message.includes('VERSION_CONFLICT')){conflict=true;notice('Another session saved changes. Export your draft, then reload to get the latest version.',true)}backup();throw e}finally{saving=null;buttons()}})();buttons();await saving;if(dirty&&!conflict)saveTimer=setTimeout(()=>save().catch(e=>notice(e.message,true)),1000)}
function paintPlayhead(){const ms=audio.currentTime*1000;$('time').textContent=`${M.time(ms)} / ${M.time(duration)}`;document.querySelectorAll('.playhead').forEach(el=>el.style.left=`${ms/duration*100}%`);$('play').textContent=audio.paused?'▶ Play':'Ⅱ Pause';$('play').setAttribute('aria-label',audio.paused?'Play audio':'Pause audio')}
async function enableMonitor(){if(!ctx)ctx=new AudioContext();if(ctx.state==='suspended')await ctx.resume();if(!mediaSource&&buffer){mediaSource=ctx.createMediaElementSource(audio);const split=ctx.createChannelSplitter(buffer.numberOfChannels);mediaSource.connect(split);for(let i=0;i<buffer.numberOfChannels;i++){const gain=ctx.createGain();split.connect(gain,i);gain.connect(ctx.destination);gains.push(gain)}setMonitor()}}
function setMonitor(){gains.forEach((g,i)=>g.gain.value=$('monitor').value==='all'?1/Math.max(1,gains.length):Number($('monitor').value)===i?1:0)}
async function playAudio(){try{await enableMonitor();await audio.play()}catch(e){toast('Could not play audio. Check the file or try again.')}}
function togglePlay(){if(!audio.src)return;if(audio.paused){if(audio.currentTime*1000>=duration)audio.currentTime=0;playAudio()}else audio.pause()}
function playSegment(s){audio.currentTime=s.start_ms/1000;loopStart=s.start_ms/1000;stopAt=s.end_ms/1000;playAudio()}
function tick(){if(!audio.paused){if(stopAt!==null&&audio.currentTime>=stopAt){if($('loop').checked&&loopStart!==null)audio.currentTime=loopStart;else{audio.pause();stopAt=null}}else if(duration&&audio.currentTime*1000>=duration)audio.pause();paintPlayhead()}requestAnimationFrame(tick)}
function exportFile(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportDraft(){const name=(data.item.display_name||'transcript').replace(/\.[^.]*$/,'').replace(/[^\p{L}\p{N}_-]/gu,'_'),format=$('exportFormat').value;if(format==='json')exportFile(JSON.stringify({schema_version:1,audio_item_id:itemId,duration_ms:duration,speakers,segments},null,2),name+'.json','application/json');else exportFile(M.subtitles(segments,speakers,format==='vtt'),name+'.'+format,'text/plain;charset=utf-8')}
function speakerRows(){$('speakerRows').innerHTML=speakers.map(s=>`<div class="speaker-settings" data-speaker-id="${s.id}"><input aria-label="Speaker name" data-speaker-name value="${esc(s.label)}" maxlength="80" ${canEdit()?'':'readonly'}><select aria-label="Audio channel" data-speaker-channel ${canEdit()?'':'disabled'}>${Array.from({length:buffer?.numberOfChannels||1},(_,i)=>`<option value="${i}" ${Number(s.channel||0)===i?'selected':''}>${buffer?.numberOfChannels===1?'Shared mono':`Channel ${i+1}`}</option>`).join('')}</select></div>`).join('')}
$('speakerSettings').onclick=()=>{speakerRows();$('speakerDialog').showModal()};$('speakerRows').onchange=e=>{if(!canEdit())return;const row=e.target.closest('[data-speaker-id]'),s=speakers.find(s=>s.id===row?.dataset.speakerId);if(!s)return;checkpoint();if(e.target.hasAttribute('data-speaker-name'))s.label=e.target.value.trim()||'Speaker';else s.channel=Number(e.target.value);changed();renderAll()};$('addSpeaker').onclick=()=>{if(!canEdit())return;if(speakers.length>=12)return toast('A maximum of 12 speakers is supported.');checkpoint();const n=Math.max(...speakers.map(s=>Number(s.id.replace('speaker-',''))))+1;speakers.push({id:'speaker-'+n,label:'Speaker '+n,channel:0});changed();renderAll();speakerRows()};
$('submit').onclick=async()=>{try{await save();if(dirty)await save();const review=data.mode==='reviewer'||(data.mode==='admin'&&['submitted','in_review'].includes(data.item.status));$('reviewTitle').textContent=review?'Submit transcription review':'Submit transcript';$('reviewDescription').textContent=review?'Approve the corrected transcript or return it to the transcriber with feedback.':'Your transcript will be locked for review after submission.';$('decisionLabel').hidden=!review;$('reviewMessage').textContent='';$('feedback').value='';$('reviewDialog').showModal()}catch(e){notice(e.message,true)}};
$('confirmSubmit').onclick=async()=>{const b=$('confirmSubmit');b.disabled=true;try{await save();if(dirty)await save();const action=$('decisionLabel').hidden?'submit':$('decision').value;if(action!=='request_changes'&&lint.some(x=>x.errors.length))throw Error('Fix the highlighted segment errors before submitting.');const r=await rpc('tx_submit',{p_item:itemId,p_revision:data.item.revision,p_action:action,p_feedback:$('feedback').value});dirty=false;data.item.revision=r.revision;data.item.status=r.status;data.history.unshift({action,revision:r.revision,feedback:$('feedback').value,created_at:new Date().toISOString()});data.editable=false;$('reviewDialog').close();$('workStatus').textContent=r.status.replaceAll('_',' ');$('saveState').textContent='Submitted';$('editNote').textContent='This submitted version is read only.';notice(action==='request_changes'?'Returned to the transcriber with your feedback.':action==='approve'?'Transcription review completed.':'Transcript submitted for review.');renderAll();try{localStorage.removeItem(backupKey)}catch(_){}}catch(e){$('reviewMessage').textContent=e.message}finally{b.disabled=false}};
$('save').onclick=()=>save().then(()=>toast('Draft saved.')).catch(e=>notice(e.message,true));$('play').onclick=togglePlay;$('back5').onclick=()=>{stopAt=null;audio.currentTime=Math.max(0,audio.currentTime-5);paintPlayhead()};$('forward5').onclick=()=>{stopAt=null;audio.currentTime=Math.min(duration/1000,audio.currentTime+5);paintPlayhead()};$('speed').onchange=e=>audio.playbackRate=Number(e.target.value);$('monitor').onchange=setMonitor;$('addSegment').onclick=()=>addSegment();$('undo').onclick=()=>{if(!canEdit()||!history.length)return;future.push(snapshot());setSnapshot(history.pop())};$('redo').onclick=()=>{if(!canEdit()||!future.length)return;history.push(snapshot());setSnapshot(future.pop())};$('zoom').oninput=()=>{$('zoomValue').textContent=$('zoom').value+'×';renderWaves()};$('speakerFilter').onchange=$('textSearch').oninput=$('diffToggle').onchange=renderRows;$('issues').onclick=()=>{showOnlyIssues=!showOnlyIssues;renderRows();toast(showOnlyIssues?'Showing segments with errors or warnings.':'Showing all segments.')};$('export').onclick=exportDraft;
$('importTranscript').onclick=()=>$('jsonFile').click();$('jsonFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('Transcript JSON must be under 5 MB.');const doc=JSON.parse(await file.text());if(!Array.isArray(doc.segments)||!Array.isArray(doc.speakers)||doc.segments.length>3000||!doc.speakers.length||doc.speakers.length>12)throw Error('Import an exported transcription JSON with speakers and segments.');const sp=doc.speakers.map((s,i)=>({id:'speaker-'+(i+1),label:String(s.label||'Speaker '+(i+1)).slice(0,80),channel:Math.max(0,Math.min(Number(s.channel)||0,(buffer?.numberOfChannels||1)-1))}));const imported=doc.segments.map(s=>{const index=doc.speakers.findIndex(p=>p.id===s.speaker_id);if(index<0||!Number.isInteger(s.start_ms)||!Number.isInteger(s.end_ms)||s.start_ms<0||s.end_ms<0||s.end_ms>14400000)throw Error('Imported segment has invalid speaker or timing.');return{id:crypto.randomUUID(),speaker_id:sp[index].id,start_ms:s.start_ms,end_ms:s.end_ms,transcript:String(s.transcript||'').slice(0,20000)}});checkpoint();segments=imported;speakers=sp;changed();renderAll();toast('Transcript imported. Undo restores your previous draft.')}catch(e){notice(e.message,true)}finally{$('jsonFile').value=''}};
$('copyId').onclick=()=>navigator.clipboard.writeText(`Transcription ${itemId}`).then(()=>toast('Support ID copied.')).catch(()=>toast(`Support ID: ${itemId}`));$('hotkeys').onclick=()=>$('hotkeyDialog').showModal();$('historyBtn').onclick=()=>{$('historyRows').innerHTML=(data?.history||[]).map(h=>`<div class="history-row"><strong>${esc(h.action.replaceAll('_',' '))}</strong> · revision ${h.revision}<small>${new Date(h.created_at).toLocaleString()}</small><p>${esc(h.feedback||'')}</p></div>`).join('')||'<p class="muted">No submissions or review decisions yet.</p>';$('historyDialog').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('discardRecovery').onclick=()=>{try{localStorage.removeItem(backupKey)}catch(_){}$('recoveryDialog').close()};$('downloadRecovery').onclick=()=>exportFile(JSON.stringify(recovery,null,2),'transcription-local-recovery.json','application/json');$('restoreRecovery').onclick=()=>{checkpoint();segments=recovery.segments;speakers=recovery.speakers;changed();renderAll();$('recoveryDialog').close()};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;const typing=/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName),mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(e=>notice(e.message,true));return}if(typing)return;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();return}if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stopAt=null;audio.currentTime=Math.max(0,Math.min(duration/1000,audio.currentTime+(e.key==='ArrowLeft'?-2:2)));paintPlayhead()}else if(e.key.toLowerCase()==='n')addSegment();else if(e.key.toLowerCase()==='s'&&selected)rowAction(selected,'split');else if(e.key==='Enter'&&selected)rowAction(selected,'play')});
window.addEventListener('beforeunload',e=>{if(dirty||saving){backup();e.preventDefault();e.returnValue=''}});window.addEventListener('pagehide',backup);window.addEventListener('resize',()=>{clearTimeout(renderWaves.timer);renderWaves.timer=setTimeout(renderWaves,150)});audio.onplay=audio.onpause=audio.ontimeupdate=paintPlayhead;audio.onended=()=>{if($('loop').checked&&selected)playSegment(segments.find(s=>s.id===selected));else paintPlayhead()};audio.onerror=()=>notice('The audio could not be played. Reload to refresh its secure link, or contact your administrator.',true);
async function init(){if(!itemId||!/^[0-9a-f-]{36}$/i.test(itemId))throw Error('Open an assigned audio module from your workspace or Transcription Lab.');const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return}backupKey=`adatacore-transcription:${user.id}:${itemId}`;data=await rpc('tx_open',{p_item:itemId});segments=data.segments||[];speakers=data.item.speakers;duration=data.item.duration_ms||data.item.duration_seconds*1000;$('projectTitle').textContent=data.project.name;$('audioTitle').textContent=data.item.display_name||data.item.recording_path.split('/').pop();$('audioMeta').textContent=`${data.item.source_project_title||'Audio'} / ${data.item.source_folder||'Root'} · ${data.mode==='reviewer'?'Transcription audit':data.mode==='admin'?'Admin workspace':'Transcription task'}`;$('workStatus').textContent=data.item.status.replaceAll('_',' ');$('saveState').textContent=data.editable?'All changes saved':'Read only';$('diffToggle').disabled=!data.item.submitted_segments?.length;if(data.mode==='admin'){$('backLink').href=`/admin/transcription?project=${data.project.id}`;$('breadcrumb').textContent='Admin / Transcription Lab'}if(data.item.feedback)notice('Review feedback: '+data.item.feedback);if(!data.editable)$('editNote').textContent='This transcript is read only. You can listen, inspect and export it.';
 const {data:signed,error}=await db.storage.from(data.item.storage_bucket).createSignedUrl(data.item.recording_path,7200);if(error)throw Error('Audio access failed: '+error.message);audio.src=signed.signedUrl;audio.load();try{ctx=new AudioContext();const response=await fetch(signed.signedUrl);if(!response.ok)throw Error('Audio download failed');buffer=await ctx.decodeAudioData(await response.arrayBuffer());duration=Math.round(buffer.duration*1000);$('channelNote').textContent=buffer.numberOfChannels===1?'Mono recording · speaker lanes share the same audio channel.':`${buffer.numberOfChannels} recorded channels · speaker labels can be mapped in Speakers.`;$('monitor').innerHTML='<option value="all">All channels</option>'+Array.from({length:buffer.numberOfChannels},(_,i)=>`<option value="${i}">Channel ${i+1}</option>`).join('')}catch(e){$('channelNote').textContent='Waveform unavailable. Audio playback and timing controls remain available.';if(Number.isFinite(audio.duration)&&audio.duration>0)duration=Math.round(audio.duration*1000)}renderAll();paintPlayhead();requestAnimationFrame(tick);try{recovery=JSON.parse(localStorage.getItem(backupKey)||'null');if(recovery?.dirty&&data.editable){const compatible=recovery.revision===data.item.revision;$('restoreRecovery').disabled=!compatible;$('recoveryMessage').textContent=compatible?'This browser has unsaved edits for this transcript. Restore them or continue with the server draft.':'A newer version exists on the server. Download your local draft before continuing; it will not overwrite the newer version.';$('recoveryDialog').showModal()}}catch(_){}
}
buttons();init().then(()=>{if(data)loadAI().catch(()=>{$('aiDraftNote').textContent='AI reference is temporarily unavailable. Your transcript is unaffected.'})}).catch(e=>{$('saveState').textContent='Unable to open';$('lanes').innerHTML='<div class="empty">Audio unavailable</div>';notice(e.message.includes('DAILY_TASK_LIMIT_REACHED')?'You have reached your daily task limit. New work unlocks at 05:30 IST.':e.message,true);buttons()});
})();
