(()=>{'use strict';
const $=id=>document.getElementById(id);
const db=supabase.createClient('https://llmhyezgcnbognmmsnzq.supabase.co','sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let projectId=Number(new URLSearchParams(location.search).get('project'))||null;
let vault={projects:[],items:[]},ai={jobs:[],language:'',auto_draft:false},selected=new Set(),sources=[],sourceSelected=new Set(),uploading=false,loadGeneration=0;
const fmt=n=>`${Math.floor((n||0)/60)}:${String(Math.floor(n||0)%60).padStart(2,'0')}`;
function notice(message,error=false){$('notice').textContent=message;$('notice').className='notice '+(error?'error':'success')}
async function rpc(name,args){const {data,error}=await db.rpc(name,args);if(error)throw Error(error.message);return data}
async function action(button,messageNode,fn){button.disabled=true;if(messageNode)messageNode.textContent='Working…';try{await fn()}catch(e){if(messageNode)messageNode.textContent=e.message;else notice(e.message,true)}finally{button.disabled=false}}
function jobMap(){return new Map((ai.jobs||[]).filter(j=>j.audio_item_id).map(j=>[j.audio_item_id,j]))}
function stateFor(item){const j=jobMap().get(item.id);if(!j)return 'waiting';if(j.status==='ready')return 'ready';if(['queued','dispatched','running'].includes(j.status))return 'processing';if(['failed','cancelled'].includes(j.status))return 'failed';return 'waiting'}
function labelFor(item){const j=jobMap().get(item.id),s=stateFor(item);if(s==='ready')return {label:'Ready to release',cls:'green',note:`${j.segment_count||0} AI segments`};if(s==='processing')return {label:j.status==='running'?'Transcribing':'Queued for AI',cls:'purple',note:'Groq Whisper is preparing this audio'};if(s==='failed')return {label:'Needs attention',cls:'ai-failed',note:j?.error_message||'AI preparation did not finish'};return {label:'Waiting for AI',cls:'',note:'Generate or retry the AI draft'} }
function filtered(){const q=$('search').value.toLowerCase().trim(),f=$('aiFilter').value;return vault.items.filter(a=>(!f||stateFor(a)===f)&&(!q||[a.display_name,a.source_project_title,a.source_folder].some(v=>String(v||'').toLowerCase().includes(q))))}
async function load(){const generation=++loadGeneration,requested=projectId;let next=await rpc('tx_get_vault',{p_project_id:requested}),nextId=requested;if(!next.projects.some(p=>p.id===nextId)&&next.projects.length){nextId=next.projects[0].id;next=await rpc('tx_get_vault',{p_project_id:nextId})}const nextAI=nextId?await rpc('tx_ai_lab',{p_project:nextId}):null;if(generation!==loadGeneration)return;vault=next;ai=nextAI||{jobs:[],language:'',auto_draft:false};projectId=nextId;selected=new Set([...selected].filter(id=>vault.items.some(a=>a.id===id)));if(projectId)history.replaceState(null,'',`/admin/transcription-vault?project=${projectId}`);render()}
function render(){const p=vault.projects.find(x=>x.id===projectId);$('projectList').innerHTML=vault.projects.map(x=>`<button class="project-option ${x.id===projectId?'active':''}" data-project="${x.id}">${esc(x.name)}<small>${x.vault_count} in Vault · ${x.queue_count} live</small></button>`).join('')||'<div class="empty">No transcription projects yet.</div>';$('projectName').textContent=p?.name||'Choose a project';$('projectDescription').textContent=p?.description||'';$('settingsLink').classList.toggle('hidden',!p);if(p)$('settingsLink').href=`/admin/project-lab?project=${p.id}`;$('queueLink').href=projectId?`/admin/transcription?project=${projectId}`:'/admin/transcription';$('importExisting').disabled=$('uploadVault').disabled=!p||p.status!=='active';const states=vault.items.map(stateFor);$('vaultCount').textContent=vault.items.length;$('readyCount').textContent=states.filter(x=>x==='ready').length;$('processingCount').textContent=states.filter(x=>x==='processing').length;$('failedCount').textContent=states.filter(x=>x==='failed').length;const language=ai.language==='hi'?'Hindi':ai.language?ai.language.toUpperCase():'Auto-detect';$('languageStatus').textContent=`${language} · Groq Whisper`;renderRows()}
function renderRows(){const rows=filtered();$('vaultRows').innerHTML=rows.map(a=>{const s=labelFor(a);return `<tr><td><input type="checkbox" data-item="${a.id}" aria-label="Select ${esc(a.display_name||'audio')}" ${selected.has(a.id)?'checked':''}></td><td><strong>${esc(a.display_name||a.recording_path.split('/').pop())}</strong><small>${esc(a.source_project_title||'Vault upload')} / ${esc(a.source_folder||'Vault')}</small></td><td>${a.duration_seconds?fmt(a.duration_seconds):'Detecting'}</td><td><span class="pill ${s.cls}">${esc(s.label)}</span><small>${esc(s.note)}</small></td><td>${a.vaulted_at||a.created_at?new Date(a.vaulted_at||a.created_at).toLocaleString():'—'}</td><td><a class="button" href="/transcription?item=${a.id}">Preview ↗</a></td></tr>`}).join('')||'<tr><td colspan="6" class="empty">Your Audio Vault is empty.<br>Upload recordings here before releasing them to transcribers.</td></tr>';$('selectionCount').textContent=`${selected.size} selected`;$('selectAll').checked=rows.length>0&&rows.every(a=>selected.has(a.id));$('release').disabled=$('retry').disabled=!projectId||!selected.size}
async function refreshAI(){if(!projectId)return;const pid=projectId,next=await rpc('tx_ai_lab',{p_project:pid});if(projectId!==pid)return;ai=next||{jobs:[]};render()}
$('projectList').onclick=e=>{const b=e.target.closest('[data-project]');if(!b)return;projectId=Number(b.dataset.project);selected.clear();load().catch(e=>notice(e.message,true))};
$('search').oninput=$('aiFilter').onchange=renderRows;
$('vaultRows').onchange=e=>{const id=e.target.dataset.item;if(!id)return;e.target.checked?selected.add(id):selected.delete(id);renderRows()};
$('selectAll').onchange=e=>{filtered().forEach(a=>e.target.checked?selected.add(a.id):selected.delete(a.id));renderRows()};
$('selectReady').onclick=()=>{filtered().filter(a=>stateFor(a)==='ready').forEach(a=>selected.add(a.id));renderRows()};
$('retry').onclick=()=>action($('retry'),null,async()=>{const r=await rpc('tx_ai_enqueue',{p_project:projectId,p_items:[...selected],p_regenerate:false});await refreshAI();notice(`${r.added} AI draft requests started; ${r.skipped} skipped because a draft is already ready or processing.`)});
$('release').onclick=()=>{$('releaseScope').textContent=`Release AI-ready audio from ${selected.size} selected Vault item${selected.size===1?'':'s'}?`;$('releaseMessage').textContent='';$('releaseDialog').showModal()};
$('releaseConfirm').onclick=()=>action($('releaseConfirm'),$('releaseMessage'),async()=>{const r=await rpc('tx_release_vault',{p_project:projectId,p_items:[...selected]});$('releaseDialog').close();selected.clear();await load();notice(`${r.released} prepared module${r.released===1?'':'s'} released to the live queue${r.skipped?`; ${r.skipped} stayed in the Vault because AI is not ready`:''}.`)});
function shownSources(){return sources.filter(s=>(!$('sourceProject').value||s.project===$('sourceProject').value)&&(!$('sourceFolder').value||s.folder===$('sourceFolder').value))}
function sourceFolders(){const rows=sources.filter(s=>!$('sourceProject').value||s.project===$('sourceProject').value);$('sourceFolder').innerHTML='<option value="">All folders</option>'+[...new Set(rows.map(s=>s.folder))].sort().map(v=>`<option>${esc(v)}</option>`).join('');renderSources()}
function renderSources(){$('sourceRows').innerHTML=shownSources().map(s=>`<label class="source-row"><input type="checkbox" data-source="${s.key}" ${sourceSelected.has(s.key)?'checked':''}><span>${esc(s.name)}<small>${esc(s.project)} / ${esc(s.folder)} · ${s.duration_seconds?fmt(s.duration_seconds):'Duration detected by AI'}</small></span></label>`).join('')||'<div class="empty">No recordings match this source.</div>';$('sourceCount').textContent=`${sourceSelected.size} selected · ${shownSources().length} shown`}
$('importExisting').onclick=()=>action($('importExisting'),null,async()=>{$('sourceMessage').textContent='';sourceSelected.clear();sources=await rpc('tx_audio_sources');$('sourceProject').innerHTML='<option value="">All projects</option>'+[...new Set(sources.map(s=>s.project))].sort().map(v=>`<option>${esc(v)}</option>`).join('');sourceFolders();$('sourceDialog').showModal()});
$('sourceProject').onchange=sourceFolders;$('sourceFolder').onchange=renderSources;
$('sourceRows').onchange=e=>{if(!e.target.dataset.source)return;e.target.checked?sourceSelected.add(e.target.dataset.source):sourceSelected.delete(e.target.dataset.source);$('sourceCount').textContent=`${sourceSelected.size} selected · ${shownSources().length} shown`};
$('sourceSelectAll').onclick=()=>{shownSources().forEach(s=>sourceSelected.add(s.key));renderSources()};
$('importConfirm').onclick=()=>action($('importConfirm'),$('sourceMessage'),async()=>{if(!sourceSelected.size)throw Error('Select at least one recording.');const r=await rpc('tx_import_sources_to_vault',{p_project_id:projectId,p_sources:sources.filter(s=>sourceSelected.has(s.key)).map(s=>({bucket:s.bucket,path:s.path}))});$('sourceDialog').close();await load();notice(`${r.imported} recording${r.imported===1?'':'s'} added to the Vault and sent for AI preparation${r.duplicates?`; ${r.duplicates} already existed in this transcription project`:''}.`)});
$('uploadVault').onclick=()=>{$('uploadResults').textContent='';$('uploadDialog').showModal()};
function duration(file){return new Promise((resolve,reject)=>{const a=new Audio(),url=URL.createObjectURL(file),finish=(fn,value)=>{clearTimeout(timer);a.removeAttribute('src');a.load();URL.revokeObjectURL(url);fn(value)},timer=setTimeout(()=>finish(reject,Error('Could not read duration; convert this file to WAV or MP3.')),15000);a.preload='metadata';a.onloadedmetadata=()=>{if(Number.isFinite(a.duration)&&a.duration>0)finish(resolve,Math.round(a.duration*1000));else{const ctx=new AudioContext();file.arrayBuffer().then(b=>ctx.decodeAudioData(b)).then(b=>finish(resolve,Math.round(b.duration*1000))).catch(()=>finish(reject,Error('Unsupported audio file.'))).finally(()=>ctx.close())}};a.onerror=()=>finish(reject,Error('This browser cannot read this audio format.'));a.src=url})}
$('uploadConfirm').onclick=()=>action($('uploadConfirm'),null,async()=>{const files=[...$('audioFiles').files];if(!files.length)throw Error('Choose audio files first.');uploading=true;$('audioFiles').disabled=true;let successes=0;try{for(const file of files){const line=document.createElement('div');line.className='file-result';line.textContent=`${file.name} — checking…`;$('uploadResults').append(line);let path=null;try{if(!file.size||file.size>24000000)throw Error('Vault files must be 24 MB or smaller.');const ext=file.name.split('.').pop().toLowerCase();if(!['mp3','mp4','mpeg','mpga','wav','m4a','webm','ogg','flac'].includes(ext))throw Error('Use WAV, MP3, M4A, MP4, WebM, OGG or FLAC.');const ms=await duration(file);if(ms>900000)throw Error('Vault audio must be 15 minutes or shorter.');path=`${projectId}/vault/${crypto.randomUUID()}.${ext}`;line.textContent=`${file.name} — uploading…`;const mime={mp3:'audio/mpeg',mpeg:'audio/mpeg',mpga:'audio/mpeg',mp4:'audio/mp4',m4a:'audio/mp4',wav:'audio/wav',webm:'audio/webm',ogg:'audio/ogg',flac:'audio/flac'}[ext];const {error}=await db.storage.from('transcription_audio').upload(path,file,{contentType:mime,upsert:false});if(error)throw error;await rpc('tx_register_vault_upload',{p_project_id:projectId,p_path:path,p_name:file.name,p_folder:$('uploadFolder').value,p_duration_ms:ms});line.textContent=`${file.name} — in Vault · AI queued`;successes++}catch(e){line.textContent=`${file.name} — ${e.message}`;line.style.color='#b33945';if(path)await db.storage.from('transcription_audio').remove([path]);}}}finally{uploading=false;$('audioFiles').disabled=false;$('audioFiles').value='';await load();notice(`${successes} of ${files.length} audio file${files.length===1?'':'s'} added to the Vault.`,successes!==files.length)}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(uploading&&b.closest('dialog').id==='uploadDialog')return;b.closest('dialog').close()});
setInterval(()=>{if(!document.hidden)refreshAI().catch(()=>{})},6000);
window.addEventListener('beforeunload',e=>{if(uploading){e.preventDefault();e.returnValue=''}});
(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return}await load()})().catch(e=>notice(e.message,true));
})();