(()=>{'use strict';
const U='https://llmhyezgcnbognmmsnzq.supabase.co',K='sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml',db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const searchInput=$('search'),results=$('results');
let currentUserId=null,currentData=null,timer=null,seq=0,busy=false,geoLoading=false;
const geoByIp=new Map();
const fmt=d=>{if(!d)return '—';const x=new Date(d);return Number.isNaN(x.getTime())?'—':x.toLocaleString()};
const ago=d=>{if(!d)return 'No activity';const t=new Date(d).getTime();if(!Number.isFinite(t))return 'No activity';const ms=Date.now()-t;if(ms<0)return 'Just now';const m=Math.floor(ms/60000);if(m<1)return 'Just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;const days=Math.floor(h/24);if(days<30)return `${days}d ago`;const months=Math.floor(days/30);if(months<12)return `${months}mo ago`;return `${Math.floor(months/12)}y ago`};
const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?';
function device(ua=''){ua=String(ua);let browser='Browser',os='Unknown device';if(/Edg\//i.test(ua))browser='Edge';else if(/OPR\//i.test(ua))browser='Opera';else if(/Chrome\//i.test(ua)&&!/Chromium/i.test(ua))browser='Chrome';else if(/Firefox\//i.test(ua))browser='Firefox';else if(/Safari\//i.test(ua)&&!/Chrome\//i.test(ua))browser='Safari';if(/Windows/i.test(ua))os='Windows';else if(/Android/i.test(ua))os='Android';else if(/iPhone|iPad|iPod/i.test(ua))os='iOS / iPadOS';else if(/Macintosh|Mac OS X/i.test(ua))os='macOS';else if(/CrOS/i.test(ua))os='ChromeOS';else if(/Linux/i.test(ua))os='Linux';return `${browser} · ${os}`}
const roleName=r=>({super_admin:'Super Admin',support:'Support',finance:'Finance',project_manager:'Project Manager',qa_manager:'QA Manager'}[r]||String(r||'').replace(/_/g,' '));
function err(text=''){const e=$('error');e.textContent=text;e.classList.toggle('visible',!!text)}
function setBusy(v){busy=v;$('refresh').disabled=v;$('refresh').textContent=v?'Loading…':'Refresh'}
async function guard(){const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return false}const {data:access,error}=await db.rpc('get_my_admin_access');if(error||!access?.allowed||!access.is_super_admin){location.replace('/admin');return false}return true}

// Move suggestions out of the animated card so no profile/tab stacking context can cover them.
if(results&&results.parentElement!==document.body)document.body.appendChild(results);
function positionResults(){if(!results.classList.contains('open'))return;const r=searchInput.getBoundingClientRect(),gap=7,maxH=Math.min(380,window.innerHeight*.55),below=window.innerHeight-r.bottom;results.style.left=`${Math.max(8,r.left)}px`;results.style.width=`${Math.min(r.width,window.innerWidth-16)}px`;results.style.right='auto';results.style.maxHeight=`${maxH}px`;if(below>=Math.min(220,maxH)){results.style.top=`${r.bottom+gap}px`;results.style.bottom='auto'}else{results.style.top='auto';results.style.bottom=`${Math.max(8,window.innerHeight-r.top+gap)}px`}}
function openResults(){results.classList.add('open');requestAnimationFrame(positionResults)}
function closeResults(){results.classList.remove('open')}

function renderSearch(rows,q){if(!rows.length){results.innerHTML=`<div class="ts-empty">No participant found for “${esc(q)}”.</div>`;openResults();return}results.innerHTML=rows.map(r=>`<button class="ts-person" type="button" data-user="${esc(r.id)}"><div class="ts-avatar">${esc(initials(r.full_name))}</div><div class="ts-person-copy"><strong>${esc(r.full_name||'Unnamed participant')}</strong><small>${esc(r.email)} · ${esc(r.uid||'No UID')}</small></div><div class="ts-person-side"><span class="pill ${r.account_status==='active'?'pill-green':'pill-red'}">${esc(r.account_status||'unknown')}</span><small>${esc(r.last_activity_at&&new Date(r.last_activity_at).getTime()>0?'Active '+ago(r.last_activity_at):'No retained activity')}</small></div></button>`).join('');openResults()}
async function search(q){q=String(q||'').trim();if(q.length<2){closeResults();results.innerHTML='';return}const n=++seq;try{const {data,error}=await db.rpc('admin_trust_safety_search',{p_query:q,p_limit:20});if(error)throw error;if(n!==seq||searchInput.value.trim()!==q)return;renderSearch(Array.isArray(data)?data:[],q)}catch(e){if(n!==seq)return;err(e.message||e)}}
function signalHtml(s){return `<div class="ts-signal" data-severity="${esc(s.severity||'info')}"><div class="ts-signal-head"><span class="ts-signal-dot"></span><strong>${esc(s.title||'Signal')}</strong></div><p>${esc(s.detail||'')}</p></div>`}
function sharedHtml(list=[]){if(!Array.isArray(list)||!list.length)return '';return list.map(u=>`<a href="/admin/trust-safety?user=${encodeURIComponent(u.id)}" data-open-user="${esc(u.id)}">${esc(u.full_name||u.email||u.uid||'Account')}</a>`).join(', ')}
function geoPlace(g){if(!g?.success)return '';return [g.city,g.region,g.country].filter(Boolean).join(', ')}
function geoShort(ip){const g=geoByIp.get(ip);if(!g)return geoLoading?'Locating…':'Location not loaded';if(!g.success)return g.message||'Location unavailable';return `${g.flag_emoji||''} ${geoPlace(g)}`.trim()||'Location unavailable'}
function distanceKm(a,b){if(!a?.success||!b?.success||!Number.isFinite(a.latitude)||!Number.isFinite(a.longitude)||!Number.isFinite(b.latitude)||!Number.isFinite(b.longitude))return null;const rad=x=>x*Math.PI/180,R=6371,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),aa=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return Math.round(R*2*Math.atan2(Math.sqrt(aa),Math.sqrt(1-aa)))}

function renderAccountDetails(data){const p=data.profile||{},roles=Array.isArray(p.staff_roles)?p.staff_roles:[],providers=Array.isArray(p.providers)?p.providers:[];const roleText=roles.length?roles.map(x=>`${roleName(x.role)}${x.project_id?` · Project ${x.project_id}`:''}`).join(', '):'Contributor only';$('accountDetails').innerHTML=[
 ['Account status',p.account_status||'Unknown'],
 ['Email verification',p.email_confirmed?`Verified ${fmt(p.email_confirmed_at)}`:'Not verified'],
 ['Account created',fmt(p.account_created_at)],
 ['Actual last sign-in',fmt(p.effective_last_sign_in_at)],
 ['Latest session activity',fmt(p.last_active_at)],
 ['Activity interpretation',p.recently_active?'Session refreshed within 15 minutes':'No session refresh in last 15 minutes'],
 ['Auth provider',providers.length?providers.join(', '):'Unknown'],
 ['SSO account',p.is_sso_user?'Yes':'No'],
 ['Staff access',roleText],
 ['Auth ban',p.banned_until&&new Date(p.banned_until)>new Date()?`Until ${fmt(p.banned_until)}`:'None active']
 ].map(x=>`<div class="ts-detail"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('')}

function renderNetworkIntel(data){const networks=Array.isArray(data.networks)?data.networks:[],latest=networks.find(n=>n.is_latest)||networks[0];if(!latest){$('networkIntel').innerHTML='<div class="ts-empty">No retained network information for this account.</div>';return}const g=geoByIp.get(latest.ip);if(!g){$('networkIntel').innerHTML=`<div class="ts-intel-place">${geoLoading?'Resolving approximate location…':'Approximate location not loaded yet'}</div><div class="ts-intel-meta"><span class="ts-ip">${esc(latest.ip)}</span> · Most recent sign-in network</div><div class="ts-loc-note">GeoIP is loaded only for Super Admin review and is never treated as GPS-level location.</div>`;return}if(!g.success){$('networkIntel').innerHTML=`<div class="ts-intel-place">Location unavailable</div><div class="ts-intel-meta"><span class="ts-ip">${esc(latest.ip)}</span> · ${esc(g.message||'GeoIP lookup failed')}</div><div class="ts-loc-note">The exact IP and session history remain available even when GeoIP cannot resolve the network.</div>`;return}const recentGeo=networks.slice(0,5).map(n=>({n,g:geoByIp.get(n.ip)})).filter(x=>x.g?.success);let shift='';if(recentGeo.length>=2){const km=distanceKm(recentGeo[0].g,recentGeo[1].g),countryChanged=recentGeo[0].g.country_code&&recentGeo[1].g.country_code&&recentGeo[0].g.country_code!==recentGeo[1].g.country_code;if((km&&km>=300)||countryChanged)shift=`<div class="ts-signal" data-severity="info" style="margin-top:10px"><div class="ts-signal-head"><span class="ts-signal-dot"></span><strong>Recent GeoIP location shift</strong></div><p>${km?`About ${km.toLocaleString()} km between two recent network lookup points. `:''}${countryChanged?'The resolved country also changed. ':''}Treat this as context only; VPNs, carriers and GeoIP error can create large jumps.</p></div>`}
$('networkIntel').innerHTML=`<div class="ts-intel-place">${esc(`${g.flag_emoji||''} ${geoPlace(g)}`.trim())}</div><div class="ts-intel-meta"><span class="ts-ip">${esc(latest.ip)}</span> · approximate network location</div><div class="ts-intel-grid"><div class="ts-intel-cell"><span>ISP</span><b>${esc(g.isp||g.organization||'Unknown')}</b></div><div class="ts-intel-cell"><span>ASN / organization</span><b>${esc([g.asn?`AS${g.asn}`:'',g.organization].filter(Boolean).join(' · ')||'Unknown')}</b></div><div class="ts-intel-cell"><span>Timezone</span><b>${esc([g.timezone,g.utc_offset].filter(Boolean).join(' · ')||'Unknown')}</b></div><div class="ts-intel-cell"><span>Approx. coordinates</span><b>${Number.isFinite(g.latitude)&&Number.isFinite(g.longitude)?`${Number(g.latitude).toFixed(3)}, ${Number(g.longitude).toFixed(3)}`:'Unknown'}</b></div></div>${shift}<div class="ts-loc-note">Approximate GeoIP provided on demand. It may identify an ISP gateway, mobile carrier exit point, VPN endpoint or nearby city rather than the user’s physical location. VPN/proxy threat detection is not enabled on the current free GeoIP tier.</div>`}

function renderNetworkHistory(data){const rows=Array.isArray(data.networks)?data.networks:[];$('networkHistory').innerHTML=rows.length?rows.map((n,i)=>{const shared=Number(n.shared_account_count||0),people=sharedHtml(n.shared_accounts);return `<article class="ts-history-row"><div class="ts-history-top"><div><div class="ts-history-title ts-ip">${esc(n.ip||'Unknown IP')}</div><div class="ts-history-sub">${esc(geoShort(n.ip))}</div></div>${n.is_latest?'<span class="pill pill-brand">Latest sign-in</span>':i===0?'<span class="pill">Recent activity</span>':''}</div><div class="ts-history-pills"><span class="pill">${Number(n.session_count||0)} session${Number(n.session_count||0)===1?'':'s'}</span><span class="pill">${Number(n.device_count||0)} device signature${Number(n.device_count||0)===1?'':'s'}</span><span class="pill">First ${esc(ago(n.first_seen))}</span><span class="pill">Active ${esc(ago(n.last_active_at))}</span></div>${shared?`<div class="ts-shared"><strong>${shared} other account${shared===1?'':'s'}</strong> used this exact IP in the last 30 days${people?`: ${people}`:''}.</div>`:''}</article>`}).join(''):'<div class="ts-empty">No retained network history.</div>'}

function renderDeviceHistory(data){const rows=Array.isArray(data.devices)?data.devices:[];$('deviceHistory').innerHTML=rows.length?rows.map((d,i)=>`<article class="ts-history-row"><div class="ts-history-top"><div><div class="ts-history-title">${esc(device(d.user_agent))}</div><div class="ts-history-sub">${esc(d.user_agent||'Unknown user-agent')}</div></div>${d.is_latest?'<span class="pill pill-brand">Latest sign-in</span>':i===0?'<span class="pill">Recent activity</span>':''}</div><div class="ts-history-pills"><span class="pill">${Number(d.session_count||0)} session${Number(d.session_count||0)===1?'':'s'}</span><span class="pill">${Number(d.network_count||0)} network${Number(d.network_count||0)===1?'':'s'}</span><span class="pill">First ${esc(ago(d.first_seen))}</span><span class="pill">Active ${esc(ago(d.last_active_at))}</span></div></article>`).join(''):'<div class="ts-empty">No retained device/browser history.</div>'}

function renderSessions(data){const sessions=Array.isArray(data.sessions)?data.sessions:[];$('sessions').innerHTML=sessions.length?sessions.map((s,i)=>{const shared=Number(s.shared_account_count||0),people=sharedHtml(s.shared_accounts),loc=s.ip?geoShort(s.ip):'Location unavailable';return `<article class="ts-session"><div class="ts-session-top"><div><strong>${i===0?'Newest retained login':'Authentication session'}</strong>${s.recently_active?' <span class="pill pill-green" style="margin-left:6px">Active recently</span>':''}</div><time>Login: ${esc(fmt(s.login_at))}</time></div><div class="ts-session-grid"><div class="ts-cell"><span>Actual login</span><b>${esc(fmt(s.login_at))}</b></div><div class="ts-cell"><span>Last session activity</span><b>${esc(fmt(s.last_active_at))}</b></div><div class="ts-cell"><span>IP / device</span><b><span class="ts-ip">${esc(s.ip||'Unavailable')}</span><br>${esc(device(s.user_agent))}</b></div><div class="ts-cell"><span>Auth level</span><b>${esc((s.aal||'aal1').toUpperCase())}</b></div></div><div class="ts-session-loc">Approx. network location: ${esc(loc)}</div>${shared?`<div class="ts-shared"><strong>${shared} other account${shared===1?'':'s'}</strong> used this exact IP in the last 30 days${people?`: ${people}`:''}. This can be legitimate on a shared network.</div>`:''}</article>`}).join(''):'<div class="ts-empty">No retained authentication sessions for this account.</div>'}

function render(data){currentData=data;const p=data.profile||{},m=data.metrics||{},signals=Array.isArray(data.signals)?data.signals:[];currentUserId=p.id||currentUserId;const level=data.attention_level||'normal';
  $('profileHead').innerHTML=`<div class="ts-id"><div class="ts-avatar">${esc(initials(p.full_name))}</div><div><div class="ts-name">${esc(p.full_name||'Unnamed participant')}</div><div class="ts-meta">${esc(p.email)} · ${esc(p.uid||'No UID')}</div><div class="ts-badges"><span class="pill ${p.account_status==='active'?'pill-green':'pill-red'}">${esc(p.account_status||'unknown')}</span><span class="pill">${p.email_confirmed?'Email verified':'Email not verified'}</span><span class="pill">Created ${esc(ago(p.account_created_at))}</span>${p.recently_active?'<span class="pill pill-green">Session active recently</span>':''}</div></div></div><div class="ts-attention ${esc(level)}">${esc(level==='normal'?'Normal':level==='review'?'Review':'Elevated')}</div>`;
  const metricData=[['Last sign-in',ago(p.effective_last_sign_in_at),fmt(p.effective_last_sign_in_at)],['Last session activity',ago(p.last_active_at),p.recently_active?'Refreshed within 15m':fmt(p.last_active_at)],['Sessions · 30d',m.sessions_30d??0,`${m.total_sessions??0} retained total`],['Networks · 30d',m.distinct_ips_30d??0,`${m.distinct_ips_24h??0} new session IPs in 24h`],['Devices · 30d',m.distinct_devices_30d??0,`${m.distinct_devices_7d??0} in last 7d`],['Shared accounts',m.shared_accounts_30d??0,'Exact IP overlap · 30d']];
  $('metrics').innerHTML=metricData.map(x=>`<div class="card ts-metric"><span>${esc(x[0])}</span><strong title="${esc(x[2])}">${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('');
  $('signals').innerHTML=signals.length?signals.map(signalHtml).join(''):'<div class="ts-signal" data-severity="info"><div class="ts-signal-head"><span class="ts-signal-dot"></span><strong>No current rule-based attention signal</strong></div><p>This does not guarantee the account is safe. It only means the current rules did not match retained authentication data.</p></div>';
  renderAccountDetails(data);renderNetworkIntel(data);renderNetworkHistory(data);renderDeviceHistory(data);renderSessions(data);
  $('disclaimer').textContent=data.disclaimer||'Network, device and location signals are correlations, not proof of abuse.';$('profile').classList.add('visible');history.replaceState(null,'',`/admin/trust-safety?user=${encodeURIComponent(p.id)}`);
}

async function loadGeo(data){const networks=Array.isArray(data?.networks)?data.networks:[],ips=[...new Set(networks.map(n=>n.ip).filter(Boolean))].slice(0,12);const missing=ips.filter(ip=>!geoByIp.has(ip));if(!missing.length){renderNetworkIntel(data);renderNetworkHistory(data);renderSessions(data);return}geoLoading=true;renderNetworkIntel(data);renderNetworkHistory(data);renderSessions(data);try{const {data:{session}}=await db.auth.getSession();if(!session?.access_token)throw new Error('Admin session is unavailable');const response=await fetch(`${U}/functions/v1/trust-safety-geoip`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:K,'Content-Type':'application/json'},body:JSON.stringify({ips:missing})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||`GeoIP lookup failed (${response.status})`);for(const g of Array.isArray(payload?.results)?payload.results:[])if(g?.ip)geoByIp.set(g.ip,g)}catch(error){for(const ip of missing)if(!geoByIp.has(ip))geoByIp.set(ip,{ip,success:false,message:String(error?.message||'Location lookup unavailable')})}finally{geoLoading=false;if(currentData===data){renderNetworkIntel(data);renderNetworkHistory(data);renderSessions(data)}}}

async function openProfile(id){if(!id||busy)return;currentUserId=id;setBusy(true);err('');closeResults();try{const {data,error}=await db.rpc('admin_trust_safety_profile',{p_user_id:id});if(error)throw error;render(data||{});loadGeo(data||{})}catch(e){err(e.message||e)}finally{setBusy(false)}}

searchInput.addEventListener('input',e=>{clearTimeout(timer);const q=e.target.value;timer=setTimeout(()=>search(q),130)});
searchInput.addEventListener('focus',e=>{if(e.target.value.trim().length>=2)search(e.target.value)});
searchInput.addEventListener('keydown',e=>{if(e.key==='Escape'){closeResults();return}if(e.key==='Enter'){const first=results.querySelector('[data-user]');if(first){e.preventDefault();openProfile(first.dataset.user)}}});
results.addEventListener('click',e=>{const b=e.target.closest('[data-user]');if(b){e.preventDefault();openProfile(b.dataset.user)}});
document.addEventListener('click',e=>{const userLink=e.target.closest('[data-open-user]');if(userLink){e.preventDefault();openProfile(userLink.dataset.openUser);return}if(!e.target.closest('.ts-search-card')&&!e.target.closest('#results'))closeResults()});
window.addEventListener('resize',positionResults,{passive:true});window.addEventListener('scroll',positionResults,{passive:true,capture:true});
$('refresh').onclick=()=>currentUserId?openProfile(currentUserId):location.reload();
(async()=>{if(!await guard())return;const id=new URLSearchParams(location.search).get('user');if(id&&/^[0-9a-f-]{36}$/i.test(id))openProfile(id)})();
})();