(()=>{'use strict';
const U='https://llmhyezgcnbognmmsnzq.supabase.co',K='sb_publishable_QfaSTpmmj6reyY-kCsmhng_7PKvCGml',db=supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentUserId=null,timer=null,seq=0,busy=false;
const fmt=d=>{if(!d)return '—';const x=new Date(d);return Number.isNaN(x.getTime())?'—':x.toLocaleString()};
const ago=d=>{if(!d)return 'No activity';const ms=Date.now()-new Date(d).getTime(),m=Math.max(0,Math.floor(ms/60000));if(m<1)return 'Just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;const days=Math.floor(h/24);return `${days}d ago`};
const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'?';
function device(ua=''){ua=String(ua);let browser='Browser',os='Unknown device';if(/Edg\//i.test(ua))browser='Edge';else if(/Chrome\//i.test(ua)&&!/Chromium/i.test(ua))browser='Chrome';else if(/Firefox\//i.test(ua))browser='Firefox';else if(/Safari\//i.test(ua)&&!/Chrome\//i.test(ua))browser='Safari';if(/Windows/i.test(ua))os='Windows';else if(/Android/i.test(ua))os='Android';else if(/iPhone|iPad|iPod/i.test(ua))os='iOS / iPadOS';else if(/Macintosh|Mac OS X/i.test(ua))os='macOS';else if(/Linux/i.test(ua))os='Linux';return `${browser} · ${os}`}
function err(text=''){const e=$('error');e.textContent=text;e.classList.toggle('visible',!!text)}
function setBusy(v){busy=v;document.body.classList.toggle('ts-loading',v);$('refresh').disabled=v}
async function guard(){const {data:{user}}=await db.auth.getUser();if(!user){location.replace('/auth');return false}const {data:access,error}=await db.rpc('get_my_admin_access');if(error||!access?.allowed||!access.is_super_admin){location.replace('/admin');return false}return true}
function renderSearch(rows,q){const box=$('results');if(!rows.length){box.innerHTML=`<div class="ts-empty">No participant found for “${esc(q)}”.</div>`;box.classList.add('open');return}box.innerHTML=rows.map(r=>`<button class="ts-person" type="button" data-user="${esc(r.id)}"><div class="ts-avatar">${esc(initials(r.full_name))}</div><div class="ts-person-copy"><strong>${esc(r.full_name||'Unnamed participant')}</strong><small>${esc(r.email)} · ${esc(r.uid||'No UID')}</small></div><span class="pill ${r.account_status==='active'?'pill-green':'pill-red'}">${esc(r.account_status||'unknown')}</span></button>`).join('');box.classList.add('open')}
async function search(q){q=String(q||'').trim();if(q.length<2){$('results').classList.remove('open');$('results').innerHTML='';return}const n=++seq;try{const {data,error}=await db.rpc('admin_trust_safety_search',{p_query:q,p_limit:20});if(error)throw error;if(n!==seq)return;renderSearch(Array.isArray(data)?data:[],q)}catch(e){if(n!==seq)return;err(e.message||e)}}
function signalHtml(s){return `<div class="ts-signal" data-severity="${esc(s.severity||'info')}"><div class="ts-signal-head"><span class="ts-signal-dot"></span><strong>${esc(s.title||'Signal')}</strong></div><p>${esc(s.detail||'')}</p></div>`}
function sharedHtml(list=[]){if(!Array.isArray(list)||!list.length)return '';return list.map(u=>`<a href="/admin/trust-safety?user=${encodeURIComponent(u.id)}">${esc(u.full_name||u.email||u.uid||'Account')}</a>`).join(', ')}
function render(data){const p=data.profile||{},m=data.metrics||{},sessions=Array.isArray(data.sessions)?data.sessions:[],signals=Array.isArray(data.signals)?data.signals:[];currentUserId=p.id||currentUserId;
  const level=data.attention_level||'normal';
  $('profileHead').innerHTML=`<div class="ts-id"><div class="ts-avatar">${esc(initials(p.full_name))}</div><div><div class="ts-name">${esc(p.full_name||'Unnamed participant')}</div><div class="ts-meta">${esc(p.email)} · ${esc(p.uid||'No UID')}</div><div class="ts-badges"><span class="pill ${p.account_status==='active'?'pill-green':'pill-red'}">${esc(p.account_status||'unknown')}</span><span class="pill">${p.email_confirmed?'Email verified':'Email not verified'}</span><span class="pill">Created ${ago(p.account_created_at)}</span></div></div></div><div class="ts-attention ${esc(level)}">${esc(level==='normal'?'Normal':level==='review'?'Review':'Elevated')}</div>`;
  const metricData=[['Last sign-in',ago(p.last_sign_in_at),fmt(p.last_sign_in_at)],['Sessions · 30d',m.sessions_30d??0,`${m.total_sessions??0} retained total`],['Networks · 30d',m.distinct_ips_30d??0,`${m.distinct_ips_24h??0} in last 24h`],['Devices · 30d',m.distinct_devices_30d??0,`${m.distinct_devices_7d??0} in last 7d`],['Shared accounts',m.shared_accounts_30d??0,'Exact IP overlap · 30d']];
  $('metrics').innerHTML=metricData.map(x=>`<div class="card ts-metric"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div>`).join('');
  $('signals').innerHTML=signals.length?signals.map(signalHtml).join(''):'<div class="ts-signal" data-severity="info"><div class="ts-signal-head"><span class="ts-signal-dot"></span><strong>No attention signals from retained session data</strong></div><p>This does not guarantee the account is safe; it means the current rule set did not find one of its defined conditions.</p></div>';
  const loc=data.location||{};$('location').innerHTML=`<strong>Approximate login location</strong><p>${loc.status==='not_collected'?'Not collected yet. '+esc(loc.message||''):esc(loc.message||'Unavailable')}</p>`;
  $('sessions').innerHTML=sessions.length?sessions.map((s,i)=>{const shared=Number(s.shared_account_count||0),people=sharedHtml(s.shared_accounts);return `<article class="ts-session"><div class="ts-session-top"><strong>${i===0?'Most recent session':'Session'}</strong><time>${esc(fmt(s.updated_at||s.created_at))}</time></div><div class="ts-session-grid"><div class="ts-cell"><span>IP address</span><b class="ts-ip">${esc(s.ip||'Unavailable')}</b></div><div class="ts-cell"><span>Device / browser</span><b>${esc(device(s.user_agent))}</b></div><div class="ts-cell"><span>Auth level</span><b>${esc((s.aal||'aal1').toUpperCase())}</b></div></div>${shared?`<div class="ts-shared"><strong>${shared} other account${shared===1?'':'s'}</strong> used this exact IP in the last 30 days${people?`: ${people}`:''}. This can be legitimate on a shared network.</div>`:''}</article>`}).join(''):'<div class="ts-empty">No retained authentication sessions for this account.</div>';
  $('disclaimer').textContent=data.disclaimer||'Network and device signals are correlations, not proof of abuse.';
  $('profile').classList.add('visible');
  history.replaceState(null,'',`/admin/trust-safety?user=${encodeURIComponent(p.id)}`);
}
async function openProfile(id){if(!id||busy)return;currentUserId=id;setBusy(true);err('');$('results').classList.remove('open');try{const {data,error}=await db.rpc('admin_trust_safety_profile',{p_user_id:id});if(error)throw error;render(data||{})}catch(e){err(e.message||e)}finally{setBusy(false)}}
$('search').addEventListener('input',e=>{clearTimeout(timer);const q=e.target.value;timer=setTimeout(()=>search(q),140)});$('search').addEventListener('focus',e=>{if(e.target.value.trim().length>=2)search(e.target.value)});$('results').addEventListener('click',e=>{const b=e.target.closest('[data-user]');if(b)openProfile(b.dataset.user)});document.addEventListener('click',e=>{if(!e.target.closest('.ts-search-card'))$('results').classList.remove('open')});$('refresh').onclick=()=>currentUserId?openProfile(currentUserId):location.reload();
(async()=>{if(!await guard())return;const id=new URLSearchParams(location.search).get('user');if(id&&/^[0-9a-f-]{36}$/i.test(id))openProfile(id)})();
})();