import assert from 'node:assert/strict';
import {normalizeDraft, audioFormat, boundedBytes, providerError} from '../supabase/functions/transcription-ai/core.mjs';
let id=0;
const response={duration:5,segments:[{speaker:'B',start:2,end:3,text:' जी। '},{speaker:'A',start:0,end:1,text:'नमस्ते।'},{speaker:'B',start:3,end:4,text:'हाँ।'}]};
const result=normalizeDraft(response,0,()=>`segment-${++id}`);
assert.equal(result.duration_ms,5000);
assert.equal(result.speakers.length,2);
assert.ok(result.speakers.every(s=>s.channel===0),'AI must not invent channel mappings');
assert.deepEqual(result.segments.map(s=>s.start_ms),[0,2000,3000]);
assert.equal(result.segments[1].speaker_id,result.segments[2].speaker_id);
assert.equal(result.segments[0].transcript,'नमस्ते।');
assert.throws(()=>normalizeDraft({segments:[]}),/No speech/);
assert.throws(()=>normalizeDraft({segments:[{start:-1,end:1,text:'x'}]}),/invalid/);
assert.throws(()=>normalizeDraft({...response,duration:901}),/15 minutes/);
assert.throws(()=>normalizeDraft({segments:Array.from({length:13},(_,i)=>({speaker:String(i),start:i,end:i+1,text:'x'}))}),/12 speakers/);
assert.throws(()=>audioFormat('test.exe'),/Convert/);
assert.equal(audioFormat('Hindi.WAV').type,'audio/wav');
assert.equal(providerError(401).code,'PROVIDER_AUTH');
assert.equal(providerError(429,'insufficient_quota').code,'PROVIDER_QUOTA');
assert.equal(providerError(429,'rate_limit_exceeded','requests','You exceeded your current quota.').code,'PROVIDER_QUOTA');
assert.equal(providerError(429,'rate_limit_exceeded','requests','Rate limit reached for requests per minute.').code,'PROVIDER_RATE_LIMIT');
assert.equal((await boundedBytes(new Response(new Uint8Array([1,2,3])),4)).length,3);
await assert.rejects(()=>boundedBytes(new Response(new Uint8Array(5)),4),/24 MB/);
await assert.rejects(()=>boundedBytes(new Response('x',{headers:{'content-length':'5'}}),4),/24 MB/);
console.log('AI core: normalization, Hindi preservation, speaker mapping, bounds and safe errors passed.');
