const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),aid='10000000-0000-4000-8000-000000000001',sid='20000000-0000-4000-8000-000000000001';
const pause=()=>new Promise(r=>setTimeout(r,20));
async function run(){
 let server={revision:0,segments:[],speakers:[{id:'speaker-1',label:'Speaker 1',channel:0},{id:'speaker-2',label:'Speaker 2',channel:0}]},calls=[],errors=[],holdSave=null;
 const virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>{if(!/navigation/.test(e.message))errors.push(e.message)});
 const dom=new JSDOM(fs.readFileSync(path.join(root,'transcription.html'),'utf8'),{url:`https://www.adatacore.com/transcription?item=${aid}`,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole});const w=dom.window;
 w.structuredClone=structuredClone;w.fetch=async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(8)});w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};w.HTMLMediaElement.prototype.load=function(){};w.HTMLMediaElement.prototype.play=async function(){};w.HTMLMediaElement.prototype.pause=function(){};
 const sample=new Float32Array(80000);for(let i=0;i<sample.length;i++)sample[i]=Math.sin(i/20)*.3;
 w.AudioContext=class{state='running';async decodeAudioData(){return {duration:10,numberOfChannels:1,getChannelData:()=>sample}}createMediaElementSource(){return{connect(){}}}createChannelSplitter(){return{connect(){}}}createGain(){return{gain:{value:1},connect(){}}}async resume(){}async close(){}};
 w.HTMLCanvasElement.prototype.getContext=()=>({beginPath(){},moveTo(){},lineTo(){},stroke(){}});
 w.supabase={createClient:()=>({auth:{getUser:async()=>({data:{user:{id:'test-user'}}})},storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'https://audio.invalid/test.wav'}})})},rpc:async(name,args)=>{calls.push({name,args});if(name==='tx_open')return{data:{item:{id:aid,display_name:'Sample audio.wav',storage_bucket:'recordings',recording_path:'sample.wav',revision:0,status:'in_progress',duration_ms:10000,speakers:server.speakers,submitted_segments:[]},project:{id:99,name:'Transcription'},mode:'contributor',editable:true,segments:[],history:[]}};if(name==='tx_save'){if(holdSave)await holdSave;assert.equal(args.p_revision,server.revision);server={revision:server.revision+1,segments:structuredClone(args.p_segments),speakers:structuredClone(args.p_speakers)};return{data:{revision:server.revision,saved:server.segments.length}}}if(name==='tx_submit')return{data:{revision:server.revision+1,status:'submitted'}};throw Error('Unexpected RPC '+name)}})};
 w.eval(fs.readFileSync(path.join(root,'transcription-model.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'transcription-editor.js'),'utf8'));await pause();
 const $=id=>w.document.getElementById(id);assert.equal($('projectTitle').textContent,'Transcription');assert.match($('channelNote').textContent,/Mono recording/);assert.equal(w.document.querySelectorAll('.speaker-lane').length,2);
 $('addSegment').click();let text=w.document.querySelector('[data-field="transcript"]');assert.ok(text);text.value='नमस्ते।';text.dispatchEvent(new w.Event('input',{bubbles:true}));assert.match($('issues').textContent,/0 errors/);
 let release;holdSave=new Promise(r=>release=r);$('save').click();await pause();text.value='नमस्ते दोस्तों।';text.dispatchEvent(new w.Event('input',{bubbles:true}));release();holdSave=null;await pause();assert.equal($('saveState').textContent,'Unsaved changes','Typing during save must stay dirty');$('save').click();await pause();assert.equal(server.segments[0].transcript,'नमस्ते दोस्तों।');assert.equal($('saveState').textContent,'All changes saved');
 $('audio').currentTime=1;w.document.querySelector('[data-action="split"]').click();assert.equal(w.document.querySelectorAll('[data-segment]').length,2);$('undo').click();assert.equal(w.document.querySelectorAll('[data-segment]').length,1);$('redo').click();assert.equal(w.document.querySelectorAll('[data-segment]').length,2);w.document.querySelector('[data-action="merge"]').click();assert.equal(w.document.querySelectorAll('[data-segment]').length,1);
 w.document.querySelector('[data-action="delete"]').click();assert.equal(w.document.querySelectorAll('[data-segment]').length,0);$('undo').click();assert.equal(w.document.querySelectorAll('[data-segment]').length,1);
 $('speakerSettings').click();assert.ok($('speakerDialog').open);$('addSpeaker').click();assert.equal(w.document.querySelectorAll('.speaker-settings').length,3);$('speakerDialog').close();
 $('save').click();await pause();$('submit').click();await pause();assert.ok($('reviewDialog').open);$('confirmSubmit').click();await pause();assert.equal($('workStatus').textContent,'submitted');assert.ok($('save').disabled);assert.ok(calls.some(x=>x.name==='tx_submit'));assert.deepEqual(errors,[]);dom.window.close();
 console.log('Transcription UI: waveform lanes, create/edit/split/merge/delete, undo/redo, speaker settings, concurrent autosave and submission passed.');
}
run().catch(e=>{console.error(e);process.exitCode=1});
