-- Adatacore platform hardening wave 1
-- Production migrations were applied through Supabase and are recorded here for source control.

-- 1) Remove anonymous execution from Admin-only RPCs.
do $$
declare r record;
begin
  for r in
    select p.oid::regprocedure as fn
    from pg_proc p
    join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public'
      and (p.proname like 'admin\_%' escape '\' or p.proname like 'tx\_admin\_%' escape '\' or p.proname='is_active_admin')
  loop
    execute format('revoke execute on function %s from anon',r.fn);
  end loop;
end $$;

-- 2) Browser error observability storage.
create table if not exists app_private.client_error_events (
  id bigint generated by default as identity primary key,
  user_id uuid,
  route text not null,
  message text not null,
  stack text,
  source text,
  line_no integer,
  column_no integer,
  user_agent text,
  release text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table app_private.client_error_events enable row level security;
revoke all on table app_private.client_error_events from anon,authenticated;
create index if not exists client_error_events_created_at_idx on app_private.client_error_events(created_at desc);
create index if not exists client_error_events_route_created_idx on app_private.client_error_events(route,created_at desc);
create index if not exists client_error_events_user_created_idx on app_private.client_error_events(user_id,created_at desc);

-- 3) Client decision history.
create table if not exists public.transcription_client_decisions (
  id bigint generated by default as identity primary key,
  share_id uuid not null references public.transcription_client_shares(id) on delete cascade,
  reviewer_name text,
  decision text not null check (decision in ('approved','changes_requested')),
  note text,
  created_at timestamptz not null default now()
);
alter table public.transcription_client_decisions enable row level security;
revoke all on table public.transcription_client_decisions from anon,authenticated;
create index if not exists transcription_client_decisions_share_created_idx on public.transcription_client_decisions(share_id,created_at desc);

-- 4) Contributor notifications.
create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null default 'info',
  title text not null,
  body text,
  link text,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.user_notifications enable row level security;
revoke all on table public.user_notifications from anon,authenticated;
create index if not exists user_notifications_user_created_idx on public.user_notifications(user_id,created_at desc);
create index if not exists user_notifications_unread_idx on public.user_notifications(user_id,created_at desc) where read_at is null;

-- 5) Immutable balance-change ledger.
create table if not exists app_private.balance_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  balance_before numeric not null,
  balance_after numeric not null,
  delta numeric not null,
  reason text not null default 'balance_change',
  actor_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table app_private.balance_ledger enable row level security;
revoke all on table app_private.balance_ledger from anon,authenticated;
create index if not exists balance_ledger_user_created_idx on app_private.balance_ledger(user_id,created_at desc);
create index if not exists balance_ledger_created_idx on app_private.balance_ledger(created_at desc);

-- 6) Staff-role framework (not yet used to narrow legacy Admin permissions).
create table if not exists public.admin_staff_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  role text not null check (role in ('super_admin','project_manager','qa_manager','finance','support')),
  project_id integer references public.project_lab(id) on delete cascade,
  active boolean not null default true,
  granted_by uuid references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,role,project_id)
);
alter table public.admin_staff_roles enable row level security;
revoke all on table public.admin_staff_roles from anon,authenticated;
create index if not exists admin_staff_roles_user_idx on public.admin_staff_roles(user_id,active);
create index if not exists admin_staff_roles_project_idx on public.admin_staff_roles(project_id,active);

-- Additional production functions/triggers in this wave:
-- admin_operations_health(), notification RPCs/triggers, get_my_quality_summary(),
-- balance ledger RPCs/trigger, staff-role RPCs, and FK performance indexes.
-- Their live definitions should be treated as canonical until consolidated into a full schema migration.
